CIRCT: circt::hw::PortConverterImpl Class Reference
circt::hw::PortConverterImpl Class Reference
#include <PortConverter.h>
Public Member Functions
LogicalResult run ()
Run port conversion.
Block * getBody () const
hw::HWMutableModuleLike getModule () const
Value createNewInput (hw::PortInfo origPort, const Twine &suffix, Type type, hw::PortInfo &newPort)
These two methods take care of allocating new ports in the correct place based on the position of 'origPort'.
void createNewOutput (hw::PortInfo origPort, const Twine &suffix, Type type, Value output, hw::PortInfo &newPort)
Same as above.
Protected Member Functions
PortConverterImpl (hw::InstanceGraphNode *moduleNode)
Protected Attributes
std::unique_ptr< PortConversionBuilder > ssb
Private Member Functions
void materializeChanges ()
Materializes/commits all of the recorded port changes to the module.
void updateInstance (hw::InstanceOp)
Updates an instance of the module.
Private Attributes
Block * body = nullptr
hw::InstanceGraphNode * moduleNode
hw::HWMutableModuleLike mod
SmallVector< std::unique_ptr< PortConversion > > loweredInputs
SmallVector< std::unique_ptr< PortConversion > > loweredOutputs
SmallVector< std::pair< unsigned, hw::PortInfo >, 0 > newInputs
SmallVector< std::pair< unsigned, hw::PortInfo >, 0 > newOutputs
SmallVector< Value, 0 > newOutputValues
Detailed Description
Definition at line 36 of file PortConverter.h.
Constructor & Destructor Documentation
PortConverterImpl()
circt::hw::PortConverterImpl::PortConverterImpl (hw::InstanceGraphNode * moduleNode) inline protected
Definition at line 58 of file PortConverter.h.
References assert(), body, circt::hw::InstanceGraphNode::getModule(), mod, and moduleNode.
Member Function Documentation
createNewInput()
Value PortConverterImpl::createNewInput (hw::PortInfo origPort, const Twine & suffix, Type type, hw::PortInfo & newPort)
These two methods take care of allocating new ports in the correct place based on the position of 'origPort'.
The new port is based on the original name and suffix. The specification for the new port is given by newPort and is recorded internally. Any changes to 'newPort' after calling this will not be reflected in the modules new port list. Will also add the new input to the block arguments of the body of the module.
Definition at line 75 of file PortConverter.cpp.
References append(), body, circt::calyx::Input, circt::hw::PortInfo::loc, circt::hw::ModulePort::name, and newInputs.
createNewOutput()
void PortConverterImpl::createNewOutput (hw::PortInfo origPort, const Twine & suffix, Type type, Value output, hw::PortInfo & newPort)
Same as above.
'output' is the value fed into the new port and is required if 'body' is non-null. Important note: cannot be a backedge which gets replaced since this isn't attached to an op until later in the pass.
Definition at line 89 of file PortConverter.cpp.
References append(), body, circt::hw::PortInfo::loc, circt::hw::ModulePort::name, newOutputs, newOutputValues, and circt::calyx::Output.
getBody()
Block* circt::hw::PortConverterImpl::getBody () const inline
Definition at line 40 of file PortConverter.h.
References body.
getModule()
hw::HWMutableModuleLike circt::hw::PortConverterImpl::getModule () const inline
Definition at line 41 of file PortConverter.h.
References mod.
Referenced by circt::hw::PortConversion::getModule().
materializeChanges()
void circt::hw::PortConverterImpl::materializeChanges () private
Materializes/commits all of the recorded port changes to the module.
run()
LogicalResult PortConverterImpl::run ()
Run port conversion.
Definition at line 104 of file PortConverter.cpp.
References body, circt::hw::ModulePortInfo::inputs(), loweredInputs, loweredOutputs, mod, moduleNode, newInputs, newOutputs, newOutputValues, circt::calyx::Output, circt::hw::ModulePortInfo::outputs(), circt::hw::ModulePortInfo::sizeInputs(), ssb, updateInstance(), and circt::hw::InstanceGraphNode::uses().
updateInstance()
void PortConverterImpl::updateInstance (hw::InstanceOp inst) private
Updates an instance of the module.
This is called after the module has been updated. It will update the instance to match the new port
Definition at line 194 of file PortConverter.cpp.
References assert(), circt::BackedgeBuilder::get(), loweredInputs, loweredOutputs, mod, circt::hw::ModulePortInfo::outputs(), and circt::hw::ModulePortInfo::sizeInputs().
Referenced by run().
Member Data Documentation
body
Block* circt::hw::PortConverterImpl::body = nullptr private
Definition at line 79 of file PortConverter.h.
Referenced by _fsm_ops_ext.MachineOp::__init__(), _esi_ops_ext.ESIPureModuleOp::add_entry_block(), _hw_ops_ext.HWModuleOp::add_entry_block(), _msft_ops_ext.MSFTModuleOp::add_entry_block(), createNewInput(), createNewOutput(), getBody(), PortConverterImpl(), and run().
loweredInputs
SmallVector<std::unique_ptr<PortConversion> > circt::hw::PortConverterImpl::loweredInputs private
Definition at line 87 of file PortConverter.h.
Referenced by run(), and updateInstance().
loweredOutputs
SmallVector<std::unique_ptr<PortConversion> > circt::hw::PortConverterImpl::loweredOutputs private
Definition at line 88 of file PortConverter.h.
Referenced by run(), and updateInstance().
mod
hw::HWMutableModuleLike circt::hw::PortConverterImpl::mod private
Definition at line 82 of file PortConverter.h.
Referenced by getModule(), PortConverterImpl(), run(), and updateInstance().
moduleNode
hw::InstanceGraphNode* circt::hw::PortConverterImpl::moduleNode private
Definition at line 81 of file PortConverter.h.
Referenced by PortConverterImpl(), and run().
newInputs
SmallVector<std::pair<unsigned, hw::PortInfo>, 0> circt::hw::PortConverterImpl::newInputs private
Definition at line 94 of file PortConverter.h.
Referenced by createNewInput(), and run().
newOutputs
SmallVector<std::pair<unsigned, hw::PortInfo>, 0> circt::hw::PortConverterImpl::newOutputs private
Definition at line 95 of file PortConverter.h.
Referenced by createNewOutput(), and run().
newOutputValues
SmallVector<Value, 0> circt::hw::PortConverterImpl::newOutputValues private
Definition at line 96 of file PortConverter.h.
Referenced by createNewOutput(), and run().
ssb
std::unique_ptr<PortConversionBuilder> circt::hw::PortConverterImpl::ssb protected
Definition at line 67 of file PortConverter.h.
Referenced by circt::hw::PortConverter< PortConversionBuilderImpl >::PortConverter(), and run().
The documentation for this class was generated from the following files:
/home/runner/work/circt-www/circt-www/circt_src/include/circt/Dialect/HW/PortConverter.h
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/HW/PortConverter.cpp