CIRCT: PipelineOutlineLowering Class Reference
PipelineOutlineLowering Class Reference
Classes
struct PipelineStageMod
Public Member Functions
StringAttr getStageRegPrefix (size_t stageIdx) override
void gatherExtInputsToStages ()
LogicalResult run () override
FailureOr< StageReturns > lowerStage (Block *stage, StageArgs argsToStage, size_t stageIndex, llvm::ArrayRef< Attribute > inputNames={}) override
NOLINTNEXTLINE(misc-no-recursion)
PipelineLowering (size_t pipelineID, ScheduledPipelineOp pipeline, OpBuilder &builder, bool clockGateRegs)
Public Member Functions inherited from PipelineLowering
PipelineLowering (size_t pipelineID, ScheduledPipelineOp pipeline, OpBuilder &builder, bool clockGateRegs)
virtual ~PipelineLowering ()=default
StageReturns emitStageBody (Block *stage, StageArgs args, llvm::ArrayRef< Attribute > registerNames, size_t stageIndex=-1)
void getStageEgressNames (size_t stageIndex, Operation *stageTerminator, bool withPipelinePrefix, StageEgressNames &egressNames)
Private Member Functions
void cloneConstantsToStages ()
hw::HWModuleOp buildPipelineLike (Twine name, TypeRange inputs, ValueRange extInputs, TypeRange outputs, bool withStall, llvm::ArrayRef< Attribute > inputNames, llvm::ArrayRef< Attribute > outputNames)
std::tuple< hw::HWModuleOp, hw::InstanceOp > buildStage (Block *stage, StageArgs args, size_t stageIndex, llvm::ArrayRef< Attribute > inputNames, StageEgressNames &egressNames)
void getStageExtInputs (Block *stage, llvm::SmallVector< Value > &extInputs)
Private Attributes
Value pipelineClk
Value pipelineRst
Value pipelineStall
hw::InstanceOp currentStageInst
hw::HWModuleOp pipelineMod
hw::InstanceOp lastStageInst
PipelineStageMod pipelineStageMod
llvm::DenseMap< Block *, llvm::SetVector< Value > > stageExtInputs
DenseMap< Value, StringAttr > extInputNames
llvm::DenseMap< Value, Value > toplevelExtInputs
Additional Inherited Members
Protected Member Functions inherited from PipelineLowering
StringAttr getPipelineBaseName ()
Protected Attributes inherited from PipelineLowering
Value parentClk
Value parentRst
size_t pipelineID
ScheduledPipelineOp pipeline
hw::HWModuleOp parentModule
OpBuilder & builder
bool clockGateRegs
StringAttr pipelineName
Detailed Description
Definition at line 417 of file PipelineToHW.cpp.
Member Function Documentation
buildPipelineLike()
hw::HWModuleOp PipelineOutlineLowering::buildPipelineLike (Twine name, TypeRange inputs, ValueRange extInputs, TypeRange outputs, bool withStall, llvm::ArrayRef< Attribute > inputNames, llvm::ArrayRef< Attribute > outputNames) inline private
Definition at line 704 of file PipelineToHW.cpp.
References assert(), builder, circt::calyx::Input, inputs, circt::calyx::Output, and outputs.
buildStage()
std::tuple<hw::HWModuleOp, hw::InstanceOp> PipelineOutlineLowering::buildStage (Block * stage, StageArgs args, size_t stageIndex, llvm::ArrayRef< Attribute > inputNames, StageEgressNames & egressNames) inline private
Definition at line 764 of file PipelineToHW.cpp.
References assert(), builder, PipelineLowering::StageArgs::data, PipelineLowering::StageArgs::enable, PipelineLowering::StageEgressNames::outNames, and PipelineLowering::StageArgs::stall.
cloneConstantsToStages()
void PipelineOutlineLowering::cloneConstantsToStages () inline private
Definition at line 668 of file PipelineToHW.cpp.
References builder.
gatherExtInputsToStages()
void PipelineOutlineLowering::gatherExtInputsToStages () inline
Definition at line 463 of file PipelineToHW.cpp.
getStageExtInputs()
void PipelineOutlineLowering::getStageExtInputs (Block * stage, llvm::SmallVector< Value > & extInputs) inline private
Definition at line 848 of file PipelineToHW.cpp.
Referenced by PipelineOutlineLowering::PipelineStageMod::PipelineStageMod().
getStageRegPrefix()
StringAttr PipelineOutlineLowering::getStageRegPrefix (size_t stageIdx) inline override virtual
Implements PipelineLowering.
Definition at line 421 of file PipelineToHW.cpp.
References builder.
lowerStage()
FailureOr<StageReturns> PipelineOutlineLowering::lowerStage (Block * stage, StageArgs argsToStage, size_t stageIndex, llvm::ArrayRef< Attribute > inputNames = {}) inline override virtual
NOLINTNEXTLINE(misc-no-recursion)
Implements PipelineLowering.
Definition at line 577 of file PipelineToHW.cpp.
PipelineLowering()
PipelineLowering::PipelineLowering inline
Definition at line 67 of file PipelineToHW.cpp.
run()
LogicalResult PipelineOutlineLowering::run () inline override virtual
Implements PipelineLowering.
Definition at line 470 of file PipelineToHW.cpp.
References builder, PipelineLowering::StageArgs::clock, PipelineLowering::StageArgs::data, PipelineLowering::StageArgs::enable, circt::calyx::direction::get(), inlineAndEraseIfEmpty(), PipelineLowering::StageArgs::reset, and PipelineLowering::StageArgs::stall.
Member Data Documentation
currentStageInst
hw::InstanceOp PipelineOutlineLowering::currentStageInst private
Definition at line 822 of file PipelineToHW.cpp.
extInputNames
DenseMap<Value, StringAttr> PipelineOutlineLowering::extInputNames private
Definition at line 839 of file PipelineToHW.cpp.
lastStageInst
hw::InstanceOp PipelineOutlineLowering::lastStageInst private
Definition at line 828 of file PipelineToHW.cpp.
pipelineClk
Value PipelineOutlineLowering::pipelineClk private
Definition at line 815 of file PipelineToHW.cpp.
pipelineMod
hw::HWModuleOp PipelineOutlineLowering::pipelineMod private
Definition at line 825 of file PipelineToHW.cpp.
pipelineRst
Value PipelineOutlineLowering::pipelineRst private
Definition at line 817 of file PipelineToHW.cpp.
pipelineStageMod
PipelineStageMod PipelineOutlineLowering::pipelineStageMod private
Definition at line 831 of file PipelineToHW.cpp.
pipelineStall
Value PipelineOutlineLowering::pipelineStall private
Definition at line 819 of file PipelineToHW.cpp.
stageExtInputs
llvm::DenseMap<Block *, llvm::SetVector<Value> > PipelineOutlineLowering::stageExtInputs private
Definition at line 836 of file PipelineToHW.cpp.
toplevelExtInputs
llvm::DenseMap<Value, Value> PipelineOutlineLowering::toplevelExtInputs private
Definition at line 843 of file PipelineToHW.cpp.
The documentation for this class was generated from the following file:
/home/runner/work/circt-www/circt-www/circt_src/lib/Conversion/PipelineToHW/PipelineToHW.cpp