CIRCT: PipelineLowering Class Reference
PipelineLowering Class Reference abstract
Classes
struct StageArgs
struct StageEgressNames
struct StageReturns
Public Member Functions
PipelineLowering (size_t pipelineID, ScheduledPipelineOp pipeline, OpBuilder &builder, bool clockGateRegs)
virtual ~PipelineLowering ()=default
virtual LogicalResult run ()=0
virtual FailureOr< StageReturns > lowerStage (Block *stage, StageArgs args, size_t stageIndex, llvm::ArrayRef< Attribute > inputNames={})=0
StageReturns emitStageBody (Block *stage, StageArgs args, llvm::ArrayRef< Attribute > registerNames, size_t stageIndex=-1)
void getStageEgressNames (size_t stageIndex, Operation *stageTerminator, bool withPipelinePrefix, StageEgressNames &egressNames)
virtual StringAttr getStageRegPrefix (size_t stageIdx)=0
Protected Member Functions
StringAttr getPipelineBaseName ()
Protected Attributes
Value parentClk
Value parentRst
size_t pipelineID
ScheduledPipelineOp pipeline
hw::HWModuleOp parentModule
OpBuilder & builder
bool clockGateRegs
StringAttr pipelineName
Detailed Description
Definition at line 65 of file PipelineToHW.cpp.
Constructor & Destructor Documentation
PipelineLowering()
PipelineLowering::PipelineLowering (size_t pipelineID, ScheduledPipelineOp pipeline, OpBuilder & builder, bool clockGateRegs) inline
Definition at line 67 of file PipelineToHW.cpp.
~PipelineLowering()
virtual PipelineLowering::~PipelineLowering () virtual default
Member Function Documentation
emitStageBody()
StageReturns PipelineLowering::emitStageBody (Block * stage, StageArgs args, llvm::ArrayRef< Attribute > registerNames, size_t stageIndex = -1) inline
Definition at line 101 of file PipelineToHW.cpp.
References assert(), builder, PipelineLowering::StageArgs::clock, circt::comb::createOrFoldNot(), PipelineLowering::StageArgs::enable, PipelineLowering::StageReturns::passthroughs, PipelineLowering::StageReturns::regs, PipelineLowering::StageArgs::reset, PipelineLowering::StageArgs::stall, and PipelineLowering::StageReturns::valid.
getPipelineBaseName()
StringAttr PipelineLowering::getPipelineBaseName () inline protected
Definition at line 296 of file PipelineToHW.cpp.
References circt::calyx::direction::get().
getStageEgressNames()
void PipelineLowering::getStageEgressNames (size_t stageIndex, Operation * stageTerminator, bool withPipelinePrefix, StageEgressNames & egressNames) inline
Definition at line 230 of file PipelineToHW.cpp.
References builder, PipelineLowering::StageEgressNames::inNames, PipelineLowering::StageEgressNames::outNames, PipelineLowering::StageEgressNames::regNames, and size().
getStageRegPrefix()
virtual StringAttr PipelineLowering::getStageRegPrefix (size_t stageIdx) pure virtual
Implemented in PipelineOutlineLowering, and PipelineInlineLowering.
lowerStage()
virtual FailureOr<StageReturns> PipelineLowering::lowerStage (Block * stage, StageArgs args, size_t stageIndex, llvm::ArrayRef< Attribute > inputNames = {}) pure virtual
Implemented in PipelineOutlineLowering, and PipelineInlineLowering.
run()
virtual LogicalResult PipelineLowering::run () pure virtual
Implemented in PipelineOutlineLowering, and PipelineInlineLowering.
Member Data Documentation
builder
OpBuilder& PipelineLowering::builder protected
Definition at line 314 of file PipelineToHW.cpp.
clockGateRegs
bool PipelineLowering::clockGateRegs protected
Definition at line 317 of file PipelineToHW.cpp.
parentClk
Value PipelineLowering::parentClk protected
Definition at line 303 of file PipelineToHW.cpp.
parentModule
hw::HWModuleOp PipelineLowering::parentModule protected
Definition at line 312 of file PipelineToHW.cpp.
parentRst
Value PipelineLowering::parentRst protected
Definition at line 305 of file PipelineToHW.cpp.
pipeline
ScheduledPipelineOp PipelineLowering::pipeline protected
Definition at line 309 of file PipelineToHW.cpp.
Referenced by PipelineOutlineLowering::PipelineStageMod::PipelineStageMod().
pipelineID
size_t PipelineLowering::pipelineID protected
Definition at line 307 of file PipelineToHW.cpp.
pipelineName
StringAttr PipelineLowering::pipelineName protected
Definition at line 321 of file PipelineToHW.cpp.
The documentation for this class was generated from the following file:
/home/runner/work/circt-www/circt-www/circt_src/lib/Conversion/PipelineToHW/PipelineToHW.cpp