CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Conversion/DCToHW/DCToHW.cpp File Reference
DCToHW.cpp File Reference
#include "circt/Conversion/DCToHW.h"
#include "../PassDetail.h"
#include "circt/Dialect/Comb/CombOps.h"
#include "circt/Dialect/DC/DCDialect.h"
#include "circt/Dialect/DC/DCOps.h"
#include "circt/Dialect/DC/DCPasses.h"
#include "circt/Dialect/ESI/ESIOps.h"
#include "circt/Dialect/ESI/ESITypes.h"
#include "circt/Dialect/HW/HWOps.h"
#include "circt/Dialect/HW/HWTypes.h"
#include "circt/Dialect/Seq/SeqOps.h"
#include "circt/Support/BackedgeBuilder.h"
#include "circt/Support/ConversionPatterns.h"
#include "circt/Support/ValueMapper.h"
#include "mlir/IR/ImplicitLocOpBuilder.h"
#include "mlir/Pass/PassManager.h"
#include "mlir/Transforms/DialectConversion.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/MathExtras.h"
#include <optional>
Typedefs
using NameUniquer = std::function< std::string(Operation *)>
Functions
static Type tupleToStruct (TupleType tuple)
static Type toHWType (Type t)
Converts the range of 'types' into a hw-dialect type.
static Type toHWType (TypeRange types)
static Type toESIHWType (Type t)
static bool isDCType (Type type)
static bool isLegalOp (Operation *op)
Returns true if the given op is considered as legal - i.e.
Typedef Documentation
NameUniquer
using NameUniquer = std::function<std::string(Operation *)>
Definition at line 40 of file DCToHW.cpp.
Function Documentation
isDCType()
static bool isDCType (Type type) static
Definition at line 800 of file DCToHW.cpp.
Referenced by isLegalOp().
isLegalOp()
static bool isLegalOp (Operation * op) static
Returns true if the given op is considered as legal - i.e.
it does not contain any dc-typed values.
Definition at line 804 of file DCToHW.cpp.
References isDCType().
toESIHWType()
static Type toESIHWType (Type t) static
Definition at line 86 of file DCToHW.cpp.
References circt::calyx::direction::get(), and toHWType().
toHWType() [1/2]
static Type toHWType (Type t) static
Converts the range of 'types' into a hw-dialect type.
Converts any type 't' into a hw-compatible type.
The range will be converted to a hw.struct type.
tuple -> hw.struct none -> i0 (tuple[...] | hw.struct)[...] -> (tuple | hw.struct)[toHwType(...)]
Definition at line 72 of file DCToHW.cpp.
References circt::calyx::direction::get(), and tupleToStruct().
Referenced by toESIHWType(), and toHWType().
toHWType() [2/2]
static Type toHWType (TypeRange types) static
Definition at line 61 of file DCToHW.cpp.
References circt::calyx::direction::get(), and toHWType().
tupleToStruct()
static Type tupleToStruct (TupleType tuple) static
Definition at line 43 of file DCToHW.cpp.
References circt::calyx::direction::get(), and circt::esi::innerType().
Referenced by toHWType().