CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/ESI/ESIServices.cpp File Reference
ESIServices.cpp File Reference
#include "PassDetails.h"
#include "circt/Dialect/Comb/CombOps.h"
#include "circt/Dialect/ESI/ESIOps.h"
#include "circt/Dialect/ESI/ESIServices.h"
#include "circt/Dialect/ESI/ESITypes.h"
#include "circt/Dialect/HW/HWAttributes.h"
#include "circt/Dialect/HW/HWOps.h"
#include "circt/Dialect/MSFT/MSFTPasses.h"
#include "circt/Dialect/SV/SVOps.h"
#include "circt/Dialect/Seq/SeqOps.h"
#include "circt/Support/BackedgeBuilder.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/ImplicitLocOpBuilder.h"
#include <memory>
#include <utility>
Functions
static LogicalResult instantiateCosimEndpointOps (ServiceImplementReqOp implReq, ServiceDeclOpInterface)
The generator for the "cosim" impl_type.
static LogicalResult instantiateSystemVerilogMemory (ServiceImplementReqOp implReq, ServiceDeclOpInterface decl)
static void emitServiceMetadata (ServiceImplementReqOp implReqOp)
Create an op which contains metadata about the soon-to-be implemented service.
Variables
static ServiceGeneratorDispatcher globalDispatcher ({{"cosim", instantiateCosimEndpointOps}, {"sv_mem", instantiateSystemVerilogMemory}}, false)
Function Documentation
emitServiceMetadata()
static void emitServiceMetadata (ServiceImplementReqOp implReqOp) static
Create an op which contains metadata about the soon-to-be implemented service.
To be used by later passes which require these data (e.g. automated software API creation).
Definition at line 401 of file ESIServices.cpp.
References assert(), and circt::calyx::direction::get().
instantiateCosimEndpointOps()
static LogicalResult instantiateCosimEndpointOps (ServiceImplementReqOp implReq, ServiceDeclOpInterface) static
The generator for the "cosim" impl_type.
Definition at line 47 of file ESIServices.cpp.
References circt::calyx::direction::get().
instantiateSystemVerilogMemory()
static LogicalResult instantiateSystemVerilogMemory (ServiceImplementReqOp implReq, ServiceDeclOpInterface decl) static
Definition at line 108 of file ESIServices.cpp.
References assert(), circt::calyx::direction::get(), circt::BackedgeBuilder::get(), and unwrap().
Variable Documentation
globalDispatcher
ServiceGeneratorDispatcher globalDispatcher({{"cosim", instantiateCosimEndpointOps}, {"sv_mem", instantiateSystemVerilogMemory}}, false) ({{"cosim", instantiateCosimEndpointOps}, {"sv_mem", instantiateSystemVerilogMemory}} , false) static
Referenced by circt::esi::ServiceGeneratorDispatcher::globalDispatcher().