CIRCT: /home/runner/work/circt-www/circt-www/circt_src/include/circt-c/Dialect/FIRRTL.h File Reference
FIRRTL.h File Reference
#include "mlir-c/IR.h"
Classes
struct FIRRTLBundleField
Typedefs
typedef struct FIRRTLBundleField FIRRTLBundleField
typedef enum FIRRTLConvention FIRRTLConvention
typedef enum FIRRTLPortDir FIRRTLPortDir
typedef enum FIRRTLNameKind FIRRTLNameKind
typedef enum FIRRTLRUW FIRRTLRUW
typedef enum FIRRTLMemDir FIRRTLMemDir
typedef enum FIRRTLEventControl FIRRTLEventControl
Enumerations
enum FIRRTLConvention { FIRRTL_CONVENTION_INTERNAL , FIRRTL_CONVENTION_SCALARIZED }
enum FIRRTLPortDir { FIRRTL_PORT_DIR_INPUT , FIRRTL_PORT_DIR_OUTPUT }
enum FIRRTLNameKind { FIRRTL_NAME_KIND_DROPPABLE_NAME , FIRRTL_NAME_KIND_INTERESTING_NAME }
enum FIRRTLRUW { FIRRTL_RUW_UNDEFINED , FIRRTL_RUW_OLD , FIRRTL_RUW_NEW }
enum FIRRTLMemDir { FIRRTL_MEM_DIR_INFER , FIRRTL_MEM_DIR_READ , FIRRTL_MEM_DIR_WRITE , FIRRTL_MEM_DIR_READ_WRITE }
enum FIRRTLEventControl { FIRRTL_EVENT_CONTROL_AT_POS_EDGE , FIRRTL_EVENT_CONTROL_AT_NEG_EDGE , FIRRTL_EVENT_CONTROL_AT_EDGE }
Functions
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION (FIRRTL, firrtl)
MLIR_CAPI_EXPORTED MlirType firrtlTypeGetUInt (MlirContext ctx, int32_t width)
MLIR_CAPI_EXPORTED MlirType firrtlTypeGetSInt (MlirContext ctx, int32_t width)
MLIR_CAPI_EXPORTED MlirType firrtlTypeGetClock (MlirContext ctx)
MLIR_CAPI_EXPORTED MlirType firrtlTypeGetReset (MlirContext ctx)
MLIR_CAPI_EXPORTED MlirType firrtlTypeGetAsyncReset (MlirContext ctx)
MLIR_CAPI_EXPORTED MlirType firrtlTypeGetAnalog (MlirContext ctx, int32_t width)
MLIR_CAPI_EXPORTED MlirType firrtlTypeGetVector (MlirContext ctx, MlirType element, size_t count)
MLIR_CAPI_EXPORTED MlirType firrtlTypeGetBundle (MlirContext ctx, size_t count, const FIRRTLBundleField *fields)
MLIR_CAPI_EXPORTED MlirAttribute firrtlAttrGetConvention (MlirContext ctx, FIRRTLConvention convention)
MLIR_CAPI_EXPORTED MlirAttribute firrtlAttrGetPortDirs (MlirContext ctx, size_t count, const FIRRTLPortDir *dirs)
MLIR_CAPI_EXPORTED MlirAttribute firrtlAttrGetNameKind (MlirContext ctx, FIRRTLNameKind nameKind)
MLIR_CAPI_EXPORTED MlirAttribute firrtlAttrGetRUW (MlirContext ctx, FIRRTLRUW ruw)
MLIR_CAPI_EXPORTED MlirAttribute firrtlAttrGetMemInit (MlirContext ctx, MlirIdentifier filename, bool isBinary, bool isInline)
MLIR_CAPI_EXPORTED MlirAttribute firrtlAttrGetMemDir (MlirContext ctx, FIRRTLMemDir dir)
MLIR_CAPI_EXPORTED MlirAttribute firrtlAttrGetEventControl (MlirContext ctx, FIRRTLEventControl eventControl)
Typedef Documentation
FIRRTLBundleField
typedef struct FIRRTLBundleField FIRRTLBundleField
FIRRTLConvention
typedef enum FIRRTLConvention FIRRTLConvention
FIRRTLEventControl
typedef enum FIRRTLEventControl FIRRTLEventControl
FIRRTLMemDir
typedef enum FIRRTLMemDir FIRRTLMemDir
FIRRTLNameKind
typedef enum FIRRTLNameKind FIRRTLNameKind
FIRRTLPortDir
typedef enum FIRRTLPortDir FIRRTLPortDir
FIRRTLRUW
typedef enum FIRRTLRUW FIRRTLRUW
Enumeration Type Documentation
FIRRTLConvention
enum FIRRTLConvention
Enumerator
FIRRTL_CONVENTION_INTERNAL
FIRRTL_CONVENTION_SCALARIZED
Definition at line 28 of file FIRRTL.h.
FIRRTLEventControl
enum FIRRTLEventControl
Enumerator
FIRRTL_EVENT_CONTROL_AT_POS_EDGE
FIRRTL_EVENT_CONTROL_AT_NEG_EDGE
FIRRTL_EVENT_CONTROL_AT_EDGE
Definition at line 61 of file FIRRTL.h.
FIRRTLMemDir
enum FIRRTLMemDir
Enumerator
FIRRTL_MEM_DIR_INFER
FIRRTL_MEM_DIR_READ
FIRRTL_MEM_DIR_WRITE
FIRRTL_MEM_DIR_READ_WRITE
Definition at line 53 of file FIRRTL.h.
FIRRTLNameKind
enum FIRRTLNameKind
Enumerator
FIRRTL_NAME_KIND_DROPPABLE_NAME
FIRRTL_NAME_KIND_INTERESTING_NAME
Definition at line 40 of file FIRRTL.h.
FIRRTLPortDir
enum FIRRTLPortDir
Enumerator
FIRRTL_PORT_DIR_INPUT
FIRRTL_PORT_DIR_OUTPUT
Definition at line 34 of file FIRRTL.h.
FIRRTLRUW
enum FIRRTLRUW
Enumerator
FIRRTL_RUW_UNDEFINED
FIRRTL_RUW_OLD
FIRRTL_RUW_NEW
Definition at line 46 of file FIRRTL.h.
Function Documentation
firrtlAttrGetConvention()
MLIR_CAPI_EXPORTED MlirAttribute firrtlAttrGetConvention (MlirContext ctx, FIRRTLConvention convention)
Definition at line 78 of file FIRRTL.cpp.
References FIRRTL_CONVENTION_INTERNAL, FIRRTL_CONVENTION_SCALARIZED, circt::calyx::direction::get(), unwrap(), and wrap().
firrtlAttrGetEventControl()
MLIR_CAPI_EXPORTED MlirAttribute firrtlAttrGetEventControl (MlirContext ctx, FIRRTLEventControl eventControl)
Definition at line 175 of file FIRRTL.cpp.
References FIRRTL_EVENT_CONTROL_AT_EDGE, FIRRTL_EVENT_CONTROL_AT_NEG_EDGE, FIRRTL_EVENT_CONTROL_AT_POS_EDGE, circt::calyx::direction::get(), unwrap(), and wrap().
firrtlAttrGetMemDir()
MLIR_CAPI_EXPORTED MlirAttribute firrtlAttrGetMemDir (MlirContext ctx, FIRRTLMemDir dir)
Definition at line 152 of file FIRRTL.cpp.
References FIRRTL_MEM_DIR_INFER, FIRRTL_MEM_DIR_READ, FIRRTL_MEM_DIR_READ_WRITE, FIRRTL_MEM_DIR_WRITE, circt::calyx::direction::get(), unwrap(), and wrap().
firrtlAttrGetMemInit()
MLIR_CAPI_EXPORTED MlirAttribute firrtlAttrGetMemInit (MlirContext ctx, MlirIdentifier filename, bool isBinary, bool isInline)
Definition at line 146 of file FIRRTL.cpp.
References circt::calyx::direction::get(), unwrap(), and wrap().
firrtlAttrGetNameKind()
MLIR_CAPI_EXPORTED MlirAttribute firrtlAttrGetNameKind (MlirContext ctx, FIRRTLNameKind nameKind)
Definition at line 109 of file FIRRTL.cpp.
References FIRRTL_NAME_KIND_DROPPABLE_NAME, FIRRTL_NAME_KIND_INTERESTING_NAME, circt::calyx::direction::get(), unwrap(), and wrap().
firrtlAttrGetPortDirs()
MLIR_CAPI_EXPORTED MlirAttribute firrtlAttrGetPortDirs (MlirContext ctx, size_t count, const FIRRTLPortDir * dirs)
Definition at line 96 of file FIRRTL.cpp.
References FIRRTL_PORT_DIR_INPUT, FIRRTL_PORT_DIR_OUTPUT, circt::firrtl::In, circt::firrtl::Out, circt::firrtl::direction::packAttribute(), unwrap(), and wrap().
firrtlAttrGetRUW()
MLIR_CAPI_EXPORTED MlirAttribute firrtlAttrGetRUW (MlirContext ctx, FIRRTLRUW ruw)
Definition at line 126 of file FIRRTL.cpp.
References FIRRTL_RUW_NEW, FIRRTL_RUW_OLD, FIRRTL_RUW_UNDEFINED, circt::calyx::direction::get(), unwrap(), and wrap().
firrtlTypeGetAnalog()
MLIR_CAPI_EXPORTED MlirType firrtlTypeGetAnalog (MlirContext ctx, int32_t width)
Definition at line 47 of file FIRRTL.cpp.
References circt::calyx::direction::get(), unwrap(), width, and wrap().
firrtlTypeGetAsyncReset()
MLIR_CAPI_EXPORTED MlirType firrtlTypeGetAsyncReset (MlirContext ctx)
Definition at line 43 of file FIRRTL.cpp.
References circt::calyx::direction::get(), unwrap(), and wrap().
firrtlTypeGetBundle()
MLIR_CAPI_EXPORTED MlirType firrtlTypeGetBundle (MlirContext ctx, size_t count, const FIRRTLBundleField * fields)
Definition at line 58 of file FIRRTL.cpp.
References assert(), circt::calyx::direction::get(), unwrap(), and wrap().
firrtlTypeGetClock()
MLIR_CAPI_EXPORTED MlirType firrtlTypeGetClock (MlirContext ctx)
Definition at line 35 of file FIRRTL.cpp.
References circt::calyx::direction::get(), unwrap(), and wrap().
firrtlTypeGetReset()
MLIR_CAPI_EXPORTED MlirType firrtlTypeGetReset (MlirContext ctx)
Definition at line 39 of file FIRRTL.cpp.
References circt::calyx::direction::get(), unwrap(), and wrap().
firrtlTypeGetSInt()
MLIR_CAPI_EXPORTED MlirType firrtlTypeGetSInt (MlirContext ctx, int32_t width)
Definition at line 31 of file FIRRTL.cpp.
References circt::calyx::direction::get(), unwrap(), width, and wrap().
firrtlTypeGetUInt()
MLIR_CAPI_EXPORTED MlirType firrtlTypeGetUInt (MlirContext ctx, int32_t width)
firrtlTypeGetVector()
MLIR_CAPI_EXPORTED MlirType firrtlTypeGetVector (MlirContext ctx, MlirType element, size_t count)
Definition at line 51 of file FIRRTL.cpp.
References assert(), circt::calyx::direction::get(), unwrap(), and wrap().
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION()
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION (FIRRTL , firrtl)