CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/HW/HWOps.cpp File Reference
HWOps.cpp File Reference
#include "circt/Dialect/HW/HWOps.h"
#include "circt/Dialect/Comb/CombOps.h"
#include "circt/Dialect/FIRRTL/FIRRTLOps.h"
#include "circt/Dialect/HW/CustomDirectiveImpl.h"
#include "circt/Dialect/HW/HWAttributes.h"
#include "circt/Dialect/HW/HWSymCache.h"
#include "circt/Dialect/HW/HWVisitors.h"
#include "circt/Dialect/HW/InstanceImplementation.h"
#include "circt/Dialect/HW/ModuleImplementation.h"
#include "circt/Support/CustomDirectiveImpl.h"
#include "circt/Support/Namespace.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/FunctionImplementation.h"
#include "mlir/IR/PatternMatch.h"
#include "llvm/ADT/BitVector.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/StringSet.h"
#include "circt/Dialect/HW/HW.cpp.inc"
Macros
#define GET_OP_CLASSES
Enumerations
enum class Delimiter { None , Paren , OptionalLessGreater }
enum ExternModKind { PlainMod , ExternMod , GenMod }
Functions
static Value foldStructExtract (Operation *inputOp, StringRef field)
static void getAsmBlockArgumentNamesImpl (mlir::Region &region, OpAsmSetValueNameFn setNameFn)
Get a special name to use when printing the entry block arguments of the region contained by an operation in this dialect.
StringAttr getArgAttrsName (MLIRContext *context)
Return the name of the arg attributes list used for both modules and instances.
StringAttr getResAttrsName (MLIRContext *context)
Return the name of the result attributes list used for both modules and instances.
template<class Op >
static bool hasAdditionalAttributes (Op op, ArrayRef< StringRef > ignoredAttrs={})
Check whether an operation has any additional attributes set beyond its standard list of attributes returned by getAttributeNames.
static LogicalResult checkAttributes (Operation *op, Attribute attr, Type type)
static ParseResult parseParamValue (OpAsmParser &p, Attribute &value, Type &resultType)
static void printParamValue (OpAsmPrinter &p, Operation *, Attribute value, Type resultType)
template<typename ModuleTy >
static void buildModule (OpBuilder &builder, OperationState &result, StringAttr name, const ModulePortInfo &ports, ArrayAttr parameters, ArrayRef< NamedAttribute > attributes, StringAttr comment)
static void modifyModuleArgs (MLIRContext *context, ArrayRef< std::pair< unsigned, PortInfo >> insertArgs, ArrayRef< unsigned > removeArgs, ArrayRef< Attribute > oldArgNames, ArrayRef< Type > oldArgTypes, ArrayRef< Attribute > oldArgAttrs, ArrayRef< Attribute > oldArgLocs, SmallVector< Attribute > &newArgNames, SmallVector< Type > &newArgTypes, SmallVector< Attribute > &newArgAttrs, SmallVector< Attribute > &newArgLocs, Block *body=nullptr)
Internal implementation of argument/result insertion and removal on modules.
static bool hasAttribute (StringRef name, ArrayRef< NamedAttribute > attrs)
template<typename ModuleTy >
static ParseResult parseHWModuleOp (OpAsmParser &parser, OperationState &result, ExternModKind modKind=PlainMod)
FunctionType getHWModuleOpType (Operation *op)
template<typename ModuleTy >
static void printModuleOp (OpAsmPrinter &p, Operation *op, ExternModKind modKind)
static LogicalResult verifyModuleCommon (Operation *module)
static ParseResult parseSliceTypes (OpAsmParser &p, Type &srcType, Type &idxType)
static void printSliceTypes (OpAsmPrinter &p, Operation *, Type srcType, Type idxType)
static LogicalResult foldCreateToSlice (ArrayCreateOp op, PatternRewriter &rewriter)
static std::optional< uint64_t > getUIntFromValue (Value value)
static ParseResult parseArrayConcatTypes (OpAsmParser &p, SmallVectorImpl< Type > &inputTypes, Type &resultType)
static void printArrayConcatTypes (OpAsmPrinter &p, Operation *, TypeRange inputTypes, Type resultType)
static bool flattenConcatOp (ArrayConcatOp op, PatternRewriter &rewriter)
static bool mergeConcatSlices (ArrayConcatOp op, PatternRewriter &rewriter)
template<typename AggregateType >
static ParseResult parseExtractOp (OpAsmParser &parser, OperationState &result)
Use the same parser for both struct_extract and union_extract since the syntax is identical.
template<typename AggType >
static void printExtractOp (OpAsmPrinter &printer, AggType op)
Use the same printer for both struct_extract and union_extract since the syntax is identical.
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 3192 of file HWOps.cpp.
Enumeration Type Documentation
Delimiter
enum Delimiter strong
Enumerator
None
Paren
OptionalLessGreater
Definition at line 103 of file HWOps.cpp.
ExternModKind
enum ExternModKind
Enumerator
PlainMod
ExternMod
GenMod
Definition at line 629 of file HWOps.cpp.
Function Documentation
buildModule()
template<typename ModuleTy > static void buildModule (OpBuilder & builder, OperationState & result, StringAttr name, const ModulePortInfo & ports, ArrayAttr parameters, ArrayRef< NamedAttribute > attributes, StringAttr comment) static
Definition at line 633 of file HWOps.cpp.
References builder, and circt::calyx::direction::get().
checkAttributes()
static LogicalResult checkAttributes (Operation * op, Attribute attr, Type type) static
Definition at line 434 of file HWOps.cpp.
References elementType.
flattenConcatOp()
static bool flattenConcatOp (ArrayConcatOp op, PatternRewriter & rewriter) static
Definition at line 2058 of file HWOps.cpp.
foldCreateToSlice()
static LogicalResult foldCreateToSlice (ArrayCreateOp op, PatternRewriter & rewriter) static
Definition at line 1794 of file HWOps.cpp.
References circt::calyx::direction::get(), circt::hw::isOffset(), and size().
foldStructExtract()
static Value foldStructExtract (Operation * inputOp, StringRef field) static
Definition at line 69 of file HWOps.cpp.
getArgAttrsName()
StringAttr getArgAttrsName (MLIRContext * context)
Return the name of the arg attributes list used for both modules and instances.
Normally we'd use the FunctionOpInterface for this, but both modules and instances use the same attribute name, and instances don't implement that interface.
Definition at line 216 of file HWOps.cpp.
Referenced by circt::hw::getArgSym().
getAsmBlockArgumentNamesImpl()
static void getAsmBlockArgumentNamesImpl (mlir::Region & region, OpAsmSetValueNameFn setNameFn) static
Get a special name to use when printing the entry block arguments of the region contained by an operation in this dialect.
Definition at line 88 of file HWOps.cpp.
References circt::hw::getModuleArgumentName().
getHWModuleOpType()
FunctionType getHWModuleOpType (Operation * op)
Definition at line 1174 of file HWOps.cpp.
Referenced by printModuleOp().
getResAttrsName()
StringAttr getResAttrsName (MLIRContext * context)
Return the name of the result attributes list used for both modules and instances.
Normally we'd use the FunctionOpInterface for this, but both modules and instances use the same attribute name, and instances don't implement that interface.
Definition at line 225 of file HWOps.cpp.
Referenced by circt::hw::getResultSym().
getUIntFromValue()
static std::optional<uint64_t> getUIntFromValue (Value value) static
Definition at line 1865 of file HWOps.cpp.
hasAdditionalAttributes()
template<class Op > static bool hasAdditionalAttributes (Op op, ArrayRef< StringRef > ignoredAttrs = {}) static
Check whether an operation has any additional attributes set beyond its standard list of attributes returned by getAttributeNames.
Definition at line 378 of file HWOps.cpp.
hasAttribute()
static bool hasAttribute (StringRef name, ArrayRef< NamedAttribute > attrs) static
Definition at line 1065 of file HWOps.cpp.
Referenced by parseHWModuleOp().
mergeConcatSlices()
static bool mergeConcatSlices (ArrayConcatOp op, PatternRewriter & rewriter) static
Definition at line 2075 of file HWOps.cpp.
References append(), circt::calyx::direction::get(), circt::hw::isOffset(), and size().
modifyModuleArgs()
static void modifyModuleArgs (MLIRContext * context, ArrayRef< std::pair< unsigned, PortInfo >> insertArgs, ArrayRef< unsigned > removeArgs, ArrayRef< Attribute > oldArgNames, ArrayRef< Type > oldArgTypes, ArrayRef< Attribute > oldArgAttrs, ArrayRef< Attribute > oldArgLocs, SmallVector< Attribute > & newArgNames, SmallVector< Type > & newArgTypes, SmallVector< Attribute > & newArgAttrs, SmallVector< Attribute > & newArgLocs, Block * body = nullptr) static
Internal implementation of argument/result insertion and removal on modules.
Definition at line 700 of file HWOps.cpp.
References assert(), and circt::calyx::direction::get().
Referenced by circt::hw::modifyModulePorts().
parseArrayConcatTypes()
static ParseResult parseArrayConcatTypes (OpAsmParser & p, SmallVectorImpl< Type > & inputTypes, Type & resultType) static
Definition at line 1992 of file HWOps.cpp.
References circt::calyx::direction::get().
parseExtractOp()
template<typename AggregateType > static ParseResult parseExtractOp (OpAsmParser & parser, OperationState & result) static
Use the same parser for both struct_extract and union_extract since the syntax is identical.
Definition at line 2389 of file HWOps.cpp.
parseHWModuleOp()
template<typename ModuleTy > static ParseResult parseHWModuleOp (OpAsmParser & parser, OperationState & result, ExternModKind modKind = PlainMod) static
Definition at line 1073 of file HWOps.cpp.
References GenMod, circt::calyx::direction::get(), hasAttribute(), circt::hw::module_like_impl::parseModuleFunctionSignature(), circt::parseOptionalParameterList(), and PlainMod.
parseParamValue()
static ParseResult parseParamValue (OpAsmParser & p, Attribute & value, Type & resultType) static
Definition at line 500 of file HWOps.cpp.
parseSliceTypes()
static ParseResult parseSliceTypes (OpAsmParser & p, Type & srcType, Type & idxType) static
Definition at line 1698 of file HWOps.cpp.
References circt::calyx::direction::get().
printArrayConcatTypes()
static void printArrayConcatTypes (OpAsmPrinter & p, Operation * , TypeRange inputTypes, Type resultType) static
Definition at line 2022 of file HWOps.cpp.
printExtractOp()
template<typename AggType > static void printExtractOp (OpAsmPrinter & printer, AggType op) static
Use the same printer for both struct_extract and union_extract since the syntax is identical.
Definition at line 2420 of file HWOps.cpp.
printModuleOp()
template<typename ModuleTy > static void printModuleOp (OpAsmPrinter & p, Operation * op, ExternModKind modKind) static
Definition at line 1181 of file HWOps.cpp.
References GenMod, getHWModuleOpType(), circt::hw::module_like_impl::printModuleSignature(), and circt::printOptionalParameterList().
printParamValue()
static void printParamValue (OpAsmPrinter & p, Operation * , Attribute value, Type resultType) static
Definition at line 508 of file HWOps.cpp.
printSliceTypes()
static void printSliceTypes (OpAsmPrinter & p, Operation * , Type srcType, Type idxType) static
Definition at line 1712 of file HWOps.cpp.
verifyModuleCommon()
static LogicalResult verifyModuleCommon (Operation * module) static
Definition at line 1248 of file HWOps.cpp.
References assert(), circt::hw::checkParameterInContext(), circt::hw::getModuleType(), and circt::hw::isAnyModule().