CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/FIRRTL/Transforms/IMDeadCodeElim.cpp File Reference
IMDeadCodeElim.cpp File Reference
#include "PassDetails.h"
#include "circt/Dialect/FIRRTL/AnnotationDetails.h"
#include "circt/Dialect/FIRRTL/FIRRTLInstanceGraph.h"
#include "circt/Dialect/FIRRTL/Passes.h"
#include "circt/Dialect/HW/InnerSymbolTable.h"
#include "mlir/IR/ImplicitLocOpBuilder.h"
#include "mlir/IR/Threading.h"
#include "mlir/Interfaces/SideEffectInterfaces.h"
#include "llvm/ADT/BitVector.h"
#include "llvm/ADT/DenseMapInfoVariant.h"
#include "llvm/ADT/PostOrderIterator.h"
#include "llvm/ADT/TinyPtrVector.h"
#include "llvm/Support/Debug.h"
Macros
#define DEBUG_TYPE "firrtl-imdeadcodeelim"
Functions
static bool hasUnknownSideEffect (Operation *op)
static bool isDeclaration (Operation *op)
Return true if this is a wire or a register or a node.
static bool isDeletableDeclaration (Operation *op)
Return true if this is a wire or register we're allowed to delete.
static bool isWeakReferencingAnnotation (Annotation anno)
Return true if the annotation is ok to drop when the target is dead.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "firrtl-imdeadcodeelim"
Definition at line 23 of file IMDeadCodeElim.cpp.
Function Documentation
hasUnknownSideEffect()
static bool hasUnknownSideEffect (Operation * op) static
Definition at line 29 of file IMDeadCodeElim.cpp.
isDeclaration()
static bool isDeclaration (Operation * op) static
Return true if this is a wire or a register or a node.
Definition at line 36 of file IMDeadCodeElim.cpp.
isDeletableDeclaration()
static bool isDeletableDeclaration (Operation * op) static
Return true if this is a wire or register we're allowed to delete.
Definition at line 41 of file IMDeadCodeElim.cpp.
References circt::firrtl::hasDontTouch().
isWeakReferencingAnnotation()
static bool isWeakReferencingAnnotation (Annotation anno) static
Return true if the annotation is ok to drop when the target is dead.
Definition at line 49 of file IMDeadCodeElim.cpp.
References circt::firrtl::Annotation::getMember(), circt::firrtl::Annotation::isClass(), and circt::firrtl::omirTrackerAnnoClass.