CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/FIRRTL/Transforms/InferResets.cpp File Reference
InferResets.cpp File Reference
#include "PassDetails.h"
#include "circt/Dialect/FIRRTL/AnnotationDetails.h"
#include "circt/Dialect/FIRRTL/FIRRTLInstanceGraph.h"
#include "circt/Dialect/FIRRTL/FIRRTLOps.h"
#include "circt/Dialect/FIRRTL/FIRRTLTypes.h"
#include "circt/Dialect/FIRRTL/FIRRTLUtils.h"
#include "circt/Dialect/FIRRTL/Passes.h"
#include "circt/Support/FieldRef.h"
#include "mlir/IR/Dominance.h"
#include "mlir/IR/ImplicitLocOpBuilder.h"
#include "mlir/IR/Threading.h"
#include "llvm/ADT/EquivalenceClasses.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/TinyPtrVector.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/Debug.h"
Classes
struct llvm::DenseMapInfo< ResetSignal >
Namespaces
llvm
Macros
#define DEBUG_TYPE "infer-resets"
Typedefs
using InstanceLike = circt::hw::HWInstanceLike
An absolute instance path.
using InstancePathRef = ArrayRef< InstanceLike >
using InstancePathVec = SmallVector< InstanceLike >
Functions
template<typename T >
static T & operator<< (T &os, InstancePathRef path)
static StringRef getTail (InstancePathRef path)
bool operator== (const ResetDomain &a, const ResetDomain &b)
bool operator!= (const ResetDomain &a, const ResetDomain &b)
static std::pair< StringAttr, FModuleOp > getResetNameAndModule (Value reset)
Return the name and parent module of a reset.
static StringAttr getResetName (Value reset)
Return the name of a reset.
static Value createZeroValue (ImplicitLocOpBuilder &builder, FIRRTLBaseType type, SmallDenseMap< FIRRTLBaseType, Value > &cache)
Construct a zero value of the given type using the given builder.
static Value createZeroValue (ImplicitLocOpBuilder &builder, FIRRTLBaseType type)
Construct a null value of the given type using the given builder.
static bool insertResetMux (ImplicitLocOpBuilder &builder, Value target, Value reset, Value resetValue)
Helper function that inserts reset multiplexer into all ConnectOps with the given target.
template<typename T >
static T & operator<< (T &os, const ResetKind &kind)
static unsigned getMaxFieldID (FIRRTLBaseType type)
static unsigned getFieldID (BundleType type, unsigned index)
static unsigned getFieldID (FVectorType type)
static unsigned getIndexForFieldID (BundleType type, unsigned fieldID)
static bool isUselessVec (FIRRTLBaseType oldType, unsigned fieldID)
static bool isUselessVec (FieldRef field)
static bool getDeclName (Value value, SmallString< 32 > &string)
static bool getFieldName (const FieldRef &fieldRef, SmallString< 32 > &string)
static bool typeContainsReset (Type type)
Check whether a type contains a ResetType.
static FIRRTLBaseType updateType (FIRRTLBaseType oldType, unsigned fieldID, FIRRTLBaseType fieldType)
Update the type of a single field within a type.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "infer-resets"
Definition at line 30 of file InferResets.cpp.
Typedef Documentation
InstanceLike
using InstanceLike = circt::hw::HWInstanceLike
An absolute instance path.
Definition at line 48 of file InferResets.cpp.
InstancePathRef
using InstancePathRef = ArrayRef<InstanceLike>
Definition at line 49 of file InferResets.cpp.
InstancePathVec
using InstancePathVec = SmallVector<InstanceLike>
Definition at line 50 of file InferResets.cpp.
Function Documentation
createZeroValue() [1/2]
static Value createZeroValue (ImplicitLocOpBuilder & builder, FIRRTLBaseType type) static
Construct a null value of the given type using the given builder.
Definition at line 172 of file InferResets.cpp.
References builder, and createZeroValue().
createZeroValue() [2/2]
static Value createZeroValue (ImplicitLocOpBuilder & builder, FIRRTLBaseType type, SmallDenseMap< FIRRTLBaseType, Value > & cache) static
Construct a zero value of the given type using the given builder.
Definition at line 115 of file InferResets.cpp.
References builder, circt::firrtl::FIRRTLTypeSwitch< T, ResultT >::Case(), circt::calyx::direction::get(), and circt::firrtl::FIRRTLBaseType::getConstType().
Referenced by createZeroValue().
getDeclName()
static bool getDeclName (Value value, SmallString< 32 > & string) static
Definition at line 664 of file InferResets.cpp.
Referenced by getFieldName().
getFieldID() [1/2]
static unsigned getFieldID (BundleType type, unsigned index) static
Definition at line 608 of file InferResets.cpp.
References assert(), and getMaxFieldID().
Referenced by getFieldName(), isUselessVec(), and updateType().
getFieldID() [2/2]
static unsigned getFieldID (FVectorType type) static
Definition at line 616 of file InferResets.cpp.
getFieldName()
static bool getFieldName (const FieldRef & fieldRef, SmallString< 32 > & string) static
Definition at line 687 of file InferResets.cpp.
References getDeclName(), circt::FieldRef::getFieldID(), getFieldID(), getIndexForFieldID(), and circt::FieldRef::getValue().
getIndexForFieldID()
static unsigned getIndexForFieldID (BundleType type, unsigned fieldID) static
Definition at line 618 of file InferResets.cpp.
References assert(), and getMaxFieldID().
Referenced by getFieldName(), isUselessVec(), and updateType().
getMaxFieldID()
static unsigned getMaxFieldID (FIRRTLBaseType type) static
Definition at line 595 of file InferResets.cpp.
References circt::firrtl::FIRRTLTypeSwitch< T, ResultT >::Case().
Referenced by getFieldID(), and getIndexForFieldID().
getResetName()
static StringAttr getResetName (Value reset) inline static
Return the name of a reset.
The reset value must either be a module port or a wire/node operation.
Definition at line 110 of file InferResets.cpp.
References getResetNameAndModule().
getResetNameAndModule()
static std::pair<StringAttr, FModuleOp> getResetNameAndModule (Value reset) static
Return the name and parent module of a reset.
The reset value must either be a module port or a wire/node operation.
Definition at line 97 of file InferResets.cpp.
Referenced by getResetName().
getTail()
static StringRef getTail (InstancePathRef path) static
Definition at line 62 of file InferResets.cpp.
insertResetMux()
static bool insertResetMux (ImplicitLocOpBuilder & builder, Value target, Value reset, Value resetValue) static
Helper function that inserts reset multiplexer into all ConnectOps with the given target.
Looks through SubfieldOp, SubindexOp, and SubaccessOp, and inserts multiplexers into connects to these subaccesses as well. Modifies the insertion location of the builder. Returns true if the resetValue was used in any way, false otherwise.
Definition at line 183 of file InferResets.cpp.
References builder, and lec::dbgs().
isUselessVec() [1/2]
static bool isUselessVec (FieldRef field) static
Definition at line 658 of file InferResets.cpp.
References circt::firrtl::getBaseType(), circt::FieldRef::getFieldID(), circt::FieldRef::getValue(), and isUselessVec().
isUselessVec() [2/2]
static bool isUselessVec (FIRRTLBaseType oldType, unsigned fieldID) static
Definition at line 632 of file InferResets.cpp.
References assert(), getFieldID(), and getIndexForFieldID().
Referenced by isUselessVec().
operator!=()
bool operator!= (const ResetDomain & a, const ResetDomain & b) inline
Definition at line 91 of file InferResets.cpp.
operator<<() [1/2]
template<typename T > static T& operator<< (T & os, const ResetKind & kind) static
Definition at line 304 of file InferResets.cpp.
operator<<() [2/2]
template<typename T > static T& operator<< (T & os, InstancePathRef path) static
Definition at line 53 of file InferResets.cpp.
operator==()
bool operator== (const ResetDomain & a, const ResetDomain & b) inline
Definition at line 88 of file InferResets.cpp.
typeContainsReset()
static bool typeContainsReset (Type type) static
Check whether a type contains a ResetType.
Definition at line 727 of file InferResets.cpp.
updateType()
static FIRRTLBaseType updateType (FIRRTLBaseType oldType, unsigned fieldID, FIRRTLBaseType fieldType) static
Update the type of a single field within a type.
Definition at line 1198 of file InferResets.cpp.
References assert(), circt::calyx::direction::get(), circt::firrtl::FIRRTLBaseType::getConstType(), getFieldID(), getIndexForFieldID(), and circt::firrtl::FIRRTLBaseType::isConst().