CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Conversion/ExportVerilog/LegalizeNames.cpp File Reference
LegalizeNames.cpp File Reference
#include "ExportVerilogInternals.h"
#include "circt/Dialect/HW/HWAttributes.h"
#include "circt/Dialect/HW/HWOps.h"
#include "circt/Dialect/Verif/VerifOps.h"
#include "circt/Support/LoweringOptions.h"
#include "mlir/IR/Threading.h"
#include "llvm/ADT/TypeSwitch.h"
Classes
class circt::ExportVerilog::GlobalNameResolver
This class keeps track of modules and interfaces that need to be renamed, as well as module ports, parameters, declarations and verif labels that need to be renamed.
Namespaces
circt
This file defines an intermediate representation for circuits acting as an abstraction for constraints defined over an SMT's solver context.
circt::ExportVerilog
Functions
static void legalizeModuleLocalNames (HWModuleOp module, const LoweringOptions &options, const GlobalNameTable &globalNameTable)
Function Documentation
legalizeModuleLocalNames()
static void legalizeModuleLocalNames (HWModuleOp module, const LoweringOptions & options, const GlobalNameTable & globalNameTable) static
Definition at line 126 of file LegalizeNames.cpp.
References circt::LoweringOptions::enforceVerifLabels, circt::calyx::direction::get(), circt::ExportVerilog::NameCollisionResolver::getLegalName(), circt::hw::getModulePortInfo(), circt::ExportVerilog::GlobalNameTable::getParameterVerilogName(), circt::ExportVerilog::getSymOpName(), and circt::ExportVerilog::NameCollisionResolver::insertUsedName().