CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/Seq/Transforms/LowerFirMem.cpp File Reference
LowerFirMem.cpp File Reference
#include "PassDetails.h"
#include "circt/Dialect/FIRRTL/FIRRTLOps.h"
#include "circt/Support/Namespace.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/Parallel.h"
#include "circt/Dialect/Seq/SeqPasses.h.inc"
Classes
struct llvm::DenseMapInfo< FirMemConfig >
Namespaces
llvm
Macros
#define DEBUG_TYPE "lower-firmem"
#define GEN_PASS_DEF_LOWERFIRMEM
Functions
static Value lookThroughWires (Value value)
Trace a value through wires to its original definition.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "lower-firmem"
Definition at line 19 of file LowerFirMem.cpp.
GEN_PASS_DEF_LOWERFIRMEM
#define GEN_PASS_DEF_LOWERFIRMEM
Definition at line 102 of file LowerFirMem.cpp.
Function Documentation
lookThroughWires()
static Value lookThroughWires (Value value) static
Trace a value through wires to its original definition.
Definition at line 210 of file LowerFirMem.cpp.
Referenced by circt::firrtl::getModuleScopedDriver(), circt::firrtl::isModuleScopedDrivenBy(), and circt::firrtl::walkDrivers().