CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/FIRRTL/Transforms/LowerIntrinsics.cpp File Reference
LowerIntrinsics.cpp File Reference
#include "PassDetails.h"
#include "circt/Dialect/FIRRTL/FIRRTLInstanceGraph.h"
#include "circt/Dialect/FIRRTL/FIRRTLOps.h"
#include "circt/Dialect/FIRRTL/FIRRTLTypes.h"
#include "circt/Dialect/FIRRTL/FIRRTLVisitors.h"
#include "circt/Dialect/FIRRTL/Namespace.h"
#include "circt/Dialect/FIRRTL/Passes.h"
#include "mlir/IR/Diagnostics.h"
#include "llvm/ADT/APSInt.h"
#include "llvm/ADT/PostOrderIterator.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Support/Debug.h"
Functions
static ParseResult hasNPorts (StringRef name, FModuleLike mod, unsigned n)
static ParseResult namedPort (StringRef name, FModuleLike mod, unsigned n, StringRef portName)
template<typename T >
static ParseResult typedPort (StringRef name, FModuleLike mod, unsigned n)
template<typename T >
static ParseResult sizedPort (StringRef name, FModuleLike mod, unsigned n, int32_t size)
static ParseResult hasNParam (StringRef name, FModuleLike mod, unsigned n, unsigned c=0)
static ParseResult namedParam (StringRef name, FModuleLike mod, StringRef paramName, bool optional=false)
static ParseResult namedIntParam (StringRef name, FModuleLike mod, StringRef paramName, bool optional=false)
static bool lowerCirctSizeof (InstanceGraph &ig, FModuleLike mod)
static bool lowerCirctIsX (InstanceGraph &ig, FModuleLike mod)
static bool lowerCirctPlusArgTest (InstanceGraph &ig, FModuleLike mod)
static bool lowerCirctPlusArgValue (InstanceGraph &ig, FModuleLike mod)
static bool lowerCirctClockGate (InstanceGraph &ig, FModuleLike mod)
template<bool isMux2>
static bool lowerCirctMuxCell (InstanceGraph &ig, FModuleLike mod)
static bool lowerCirctLTLAnd (InstanceGraph &ig, FModuleLike mod)
static bool lowerCirctLTLOr (InstanceGraph &ig, FModuleLike mod)
static bool lowerCirctLTLDelay (InstanceGraph &ig, FModuleLike mod)
static bool lowerCirctLTLConcat (InstanceGraph &ig, FModuleLike mod)
static bool lowerCirctLTLNot (InstanceGraph &ig, FModuleLike mod)
static bool lowerCirctLTLImplication (InstanceGraph &ig, FModuleLike mod)
static bool lowerCirctLTLEventually (InstanceGraph &ig, FModuleLike mod)
static bool lowerCirctLTLClock (InstanceGraph &ig, FModuleLike mod)
static bool lowerCirctLTLDisable (InstanceGraph &ig, FModuleLike mod)
template<class Op >
static bool lowerCirctVerif (InstanceGraph &ig, FModuleLike mod)
Variables
std::pair< const char *, std::function< bool(InstanceGraph &, FModuleLike)> > intrinsics []
Function Documentation
hasNParam()
static ParseResult hasNParam (StringRef name, FModuleLike mod, unsigned n, unsigned c = 0) static
Definition at line 91 of file LowerIntrinsics.cpp.
Referenced by lowerCirctClockGate(), lowerCirctIsX(), lowerCirctLTLAnd(), lowerCirctLTLClock(), lowerCirctLTLConcat(), lowerCirctLTLDelay(), lowerCirctLTLDisable(), lowerCirctLTLEventually(), lowerCirctLTLImplication(), lowerCirctLTLNot(), lowerCirctLTLOr(), lowerCirctPlusArgTest(), lowerCirctPlusArgValue(), lowerCirctSizeof(), and lowerCirctVerif().
hasNPorts()
static ParseResult hasNPorts (StringRef name, FModuleLike mod, unsigned n) static
Definition at line 40 of file LowerIntrinsics.cpp.
Referenced by lowerCirctClockGate(), lowerCirctIsX(), lowerCirctLTLAnd(), lowerCirctLTLClock(), lowerCirctLTLConcat(), lowerCirctLTLDelay(), lowerCirctLTLDisable(), lowerCirctLTLEventually(), lowerCirctLTLImplication(), lowerCirctLTLNot(), lowerCirctLTLOr(), lowerCirctMuxCell(), lowerCirctPlusArgTest(), lowerCirctPlusArgValue(), lowerCirctSizeof(), and lowerCirctVerif().
lowerCirctClockGate()
static bool lowerCirctClockGate (InstanceGraph & ig, FModuleLike mod) static
Definition at line 229 of file LowerIntrinsics.cpp.
References builder, circt::firrtl::en, hasNParam(), hasNPorts(), circt::hw::InstanceGraphBase::lookup(), namedPort(), and circt::hw::InstanceGraphNode::uses().
lowerCirctIsX()
static bool lowerCirctIsX (InstanceGraph & ig, FModuleLike mod) static
Definition at line 166 of file LowerIntrinsics.cpp.
References builder, hasNParam(), hasNPorts(), circt::hw::InstanceGraphBase::lookup(), namedPort(), size(), and circt::hw::InstanceGraphNode::uses().
lowerCirctLTLAnd()
static bool lowerCirctLTLAnd (InstanceGraph & ig, FModuleLike mod) static
Definition at line 298 of file LowerIntrinsics.cpp.
References builder, hasNParam(), hasNPorts(), circt::hw::InstanceGraphBase::lookup(), namedPort(), and circt::hw::InstanceGraphNode::uses().
lowerCirctLTLClock()
static bool lowerCirctLTLClock (InstanceGraph & ig, FModuleLike mod) static
Definition at line 483 of file LowerIntrinsics.cpp.
References builder, hasNParam(), hasNPorts(), circt::hw::InstanceGraphBase::lookup(), namedPort(), and circt::hw::InstanceGraphNode::uses().
lowerCirctLTLConcat()
static bool lowerCirctLTLConcat (InstanceGraph & ig, FModuleLike mod) static
Definition at line 388 of file LowerIntrinsics.cpp.
References builder, hasNParam(), hasNPorts(), circt::hw::InstanceGraphBase::lookup(), namedPort(), and circt::hw::InstanceGraphNode::uses().
lowerCirctLTLDelay()
static bool lowerCirctLTLDelay (InstanceGraph & ig, FModuleLike mod) static
Definition at line 348 of file LowerIntrinsics.cpp.
References builder, circt::calyx::direction::get(), hasNParam(), hasNPorts(), circt::hw::InstanceGraphBase::lookup(), namedIntParam(), namedPort(), and circt::hw::InstanceGraphNode::uses().
lowerCirctLTLDisable()
static bool lowerCirctLTLDisable (InstanceGraph & ig, FModuleLike mod) static
Definition at line 509 of file LowerIntrinsics.cpp.
References builder, hasNParam(), hasNPorts(), circt::hw::InstanceGraphBase::lookup(), namedPort(), and circt::hw::InstanceGraphNode::uses().
lowerCirctLTLEventually()
static bool lowerCirctLTLEventually (InstanceGraph & ig, FModuleLike mod) static
Definition at line 461 of file LowerIntrinsics.cpp.
References builder, hasNParam(), hasNPorts(), circt::hw::InstanceGraphBase::lookup(), namedPort(), and circt::hw::InstanceGraphNode::uses().
lowerCirctLTLImplication()
static bool lowerCirctLTLImplication (InstanceGraph & ig, FModuleLike mod) static
Definition at line 435 of file LowerIntrinsics.cpp.
References builder, hasNParam(), hasNPorts(), circt::hw::InstanceGraphBase::lookup(), namedPort(), and circt::hw::InstanceGraphNode::uses().
lowerCirctLTLNot()
static bool lowerCirctLTLNot (InstanceGraph & ig, FModuleLike mod) static
Definition at line 413 of file LowerIntrinsics.cpp.
References builder, hasNParam(), hasNPorts(), circt::hw::InstanceGraphBase::lookup(), namedPort(), and circt::hw::InstanceGraphNode::uses().
lowerCirctLTLOr()
static bool lowerCirctLTLOr (InstanceGraph & ig, FModuleLike mod) static
Definition at line 323 of file LowerIntrinsics.cpp.
References builder, hasNParam(), hasNPorts(), circt::hw::InstanceGraphBase::lookup(), namedPort(), and circt::hw::InstanceGraphNode::uses().
lowerCirctMuxCell()
template<bool isMux2> static bool lowerCirctMuxCell (InstanceGraph & ig, FModuleLike mod) static
Definition at line 255 of file LowerIntrinsics.cpp.
References builder, hasNPorts(), circt::hw::InstanceGraphBase::lookup(), namedPort(), and circt::hw::InstanceGraphNode::uses().
lowerCirctPlusArgTest()
static bool lowerCirctPlusArgTest (InstanceGraph & ig, FModuleLike mod) static
Definition at line 186 of file LowerIntrinsics.cpp.
References builder, hasNParam(), hasNPorts(), circt::hw::InstanceGraphBase::lookup(), namedParam(), namedPort(), and circt::hw::InstanceGraphNode::uses().
lowerCirctPlusArgValue()
static bool lowerCirctPlusArgValue (InstanceGraph & ig, FModuleLike mod) static
Definition at line 206 of file LowerIntrinsics.cpp.
References builder, hasNParam(), hasNPorts(), circt::hw::InstanceGraphBase::lookup(), namedParam(), namedPort(), and circt::hw::InstanceGraphNode::uses().
lowerCirctSizeof()
static bool lowerCirctSizeof (InstanceGraph & ig, FModuleLike mod) static
Definition at line 145 of file LowerIntrinsics.cpp.
References builder, hasNParam(), hasNPorts(), circt::hw::InstanceGraphBase::lookup(), namedPort(), size(), and circt::hw::InstanceGraphNode::uses().
lowerCirctVerif()
template<class Op > static bool lowerCirctVerif (InstanceGraph & ig, FModuleLike mod) static
Definition at line 537 of file LowerIntrinsics.cpp.
References builder, hasNParam(), hasNPorts(), circt::hw::InstanceGraphBase::lookup(), namedParam(), namedPort(), and circt::hw::InstanceGraphNode::uses().
namedIntParam()
static ParseResult namedIntParam (StringRef name, FModuleLike mod, StringRef paramName, bool optional = false) static
Definition at line 126 of file LowerIntrinsics.cpp.
Referenced by lowerCirctLTLDelay().
namedParam()
static ParseResult namedParam (StringRef name, FModuleLike mod, StringRef paramName, bool optional = false) static
Definition at line 107 of file LowerIntrinsics.cpp.
Referenced by lowerCirctPlusArgTest(), lowerCirctPlusArgValue(), and lowerCirctVerif().
namedPort()
static ParseResult namedPort (StringRef name, FModuleLike mod, unsigned n, StringRef portName) static
Definition at line 49 of file LowerIntrinsics.cpp.
References circt::hw::instance_like_impl::getName().
Referenced by lowerCirctClockGate(), lowerCirctIsX(), lowerCirctLTLAnd(), lowerCirctLTLClock(), lowerCirctLTLConcat(), lowerCirctLTLDelay(), lowerCirctLTLDisable(), lowerCirctLTLEventually(), lowerCirctLTLImplication(), lowerCirctLTLNot(), lowerCirctLTLOr(), lowerCirctMuxCell(), lowerCirctPlusArgTest(), lowerCirctPlusArgValue(), lowerCirctSizeof(), and lowerCirctVerif().
sizedPort()
template<typename T > static ParseResult sizedPort (StringRef name, FModuleLike mod, unsigned n, int32_t size) static
Definition at line 79 of file LowerIntrinsics.cpp.
References size().
typedPort()
template<typename T > static ParseResult typedPort (StringRef name, FModuleLike mod, unsigned n) static
Definition at line 65 of file LowerIntrinsics.cpp.
Variable Documentation
intrinsics
std::pair<const char *, std::function<bool(InstanceGraph &, FModuleLike)> > intrinsics[]
Definition at line 564 of file LowerIntrinsics.cpp.