CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Conversion/StandardToHandshake/MaximizeSSA.cpp File Reference
MaximizeSSA.cpp File Reference
#include "../PassDetail.h"
#include "circt/Conversion/StandardToHandshake.h"
#include "circt/Transforms/Passes.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/IR/MLIRContext.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Support/LogicalResult.h"
#include "mlir/Transforms/DialectConversion.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/Support/raw_ostream.h"
Namespaces
circt
This file defines an intermediate representation for circuits acting as an abstraction for constraints defined over an SMT's solver context.
Functions
static Block * getDefiningBlock (Value value)
static LogicalResult addArgToTerminator (Block *block, Block *predBlock, Value value)
std::unique_ptr< mlir::Pass > circt::createMaximizeSSAPass ()
Function Documentation
addArgToTerminator()
static LogicalResult addArgToTerminator (Block * block, Block * predBlock, Value value) static
Definition at line 39 of file MaximizeSSA.cpp.
Referenced by circt::maximizeSSA().
getDefiningBlock()
static Block* getDefiningBlock (Value value) static
Definition at line 28 of file MaximizeSSA.cpp.
References assert().
Referenced by circt::isRegionSSAMaximized(), and circt::maximizeSSA().