CIRCT: circt::seq Namespace Reference
circt::seq Namespace Reference
Functions
bool isValidIndexValues (Value hlmemHandle, ValueRange addresses)
std::unique_ptr< mlir::Pass > createSeqLowerToSVPass (std::optional< bool > lowerToAlwaysFF={})
std::unique_ptr< mlir::Pass > createLowerSeqFIRRTLInitToSV ()
std::unique_ptr< mlir::Pass > createSeqFIRRTLLowerToSVPass (const LowerSeqFIRRTLToSVOptions &options={})
std::unique_ptr< mlir::Pass > createLowerSeqHLMemPass ()
std::unique_ptr< mlir::Pass > createExternalizeClockGatePass (const ExternalizeClockGateOptions &options={})
std::unique_ptr< mlir::Pass > createLowerFirMemPass ()
std::unique_ptr< mlir::Pass > createLowerSeqFIFOPass ()
Function Documentation
createExternalizeClockGatePass()
std::unique_ptr< Pass > circt::seq::createExternalizeClockGatePass (const ExternalizeClockGateOptions & options = {})
Definition at line 104 of file ExternalizeClockGate.cpp.
Referenced by circt::firtool::populateHWToSV().
createLowerFirMemPass()
std::unique_ptr< Pass > circt::seq::createLowerFirMemPass ()
Definition at line 573 of file LowerFirMem.cpp.
Referenced by circt::firtool::populateHWToSV().
createLowerSeqFIFOPass()
std::unique_ptr< Pass > circt::seq::createLowerSeqFIFOPass ()
Definition at line 195 of file LowerSeqFIFO.cpp.
createLowerSeqFIRRTLInitToSV()
std::unique_ptr< Pass > circt::seq::createLowerSeqFIRRTLInitToSV ()
Definition at line 869 of file LowerSeqToSV.cpp.
createLowerSeqHLMemPass()
std::unique_ptr< Pass > circt::seq::createLowerSeqHLMemPass ()
Definition at line 176 of file LowerSeqHLMem.cpp.
createSeqFIRRTLLowerToSVPass()
std::unique_ptr< Pass > circt::seq::createSeqFIRRTLLowerToSVPass (const LowerSeqFIRRTLToSVOptions & options = {})
Definition at line 873 of file LowerSeqToSV.cpp.
Referenced by circt::firtool::populateHWToSV().
createSeqLowerToSVPass()
std::unique_ptr< Pass > circt::seq::createSeqLowerToSVPass (std::optional< bool > lowerToAlwaysFF = {})
Definition at line 862 of file LowerSeqToSV.cpp.
isValidIndexValues()
bool circt::seq::isValidIndexValues (Value hlmemHandle, ValueRange addresses)
Definition at line 51 of file SeqOps.cpp.