CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/CAPI/Dialect/OM.cpp File Reference
OM.cpp File Reference
#include "circt-c/Dialect/OM.h"
#include "circt/Dialect/OM/Evaluator/Evaluator.h"
#include "circt/Dialect/OM/OMAttributes.h"
#include "circt/Dialect/OM/OMDialect.h"
#include "mlir/CAPI/Registration.h"
#include "mlir/CAPI/Wrap.h"
Functions
bool omTypeIsAClassType (MlirType type)
Is the Type a ClassType.
static OMObject wrap (std::shared_ptr< Object > object)
Define our own wrap and unwrap instead of using the usual macro.
static std::shared_ptr< Object > unwrap (OMObject c)
OMEvaluator omEvaluatorNew (MlirModule mod)
Construct an Evaluator with an IR module.
OMObject omEvaluatorInstantiate (OMEvaluator evaluator, MlirAttribute className, intptr_t nActualParams, MlirAttribute const *actualParams)
Use the Evaluator to Instantiate an Object from its class name and actual parameters.
MlirModule omEvaluatorGetModule (OMEvaluator evaluator)
Get the Module the Evaluator is built from.
bool omEvaluatorObjectIsNull (OMObject object)
Query if the Object is null.
MlirType omEvaluatorObjectGetType (OMObject object)
Get the Type from an Object, which will be a ClassType.
MlirAttribute omEvaluatorObjectGetFieldNames (OMObject object)
Get an ArrayAttr with the names of the fields in an Object.
OMObjectValue omEvaluatorObjectGetField (OMObject object, MlirAttribute name)
Get a field from an Object, which must contain a field of that name.
bool omEvaluatorObjectValueIsNull (OMObjectValue objectValue)
bool omEvaluatorObjectValueIsAObject (OMObjectValue objectValue)
Query if the ObjectValue is an Object.
OMObject omEvaluatorObjectValueGetObject (OMObjectValue objectValue)
Get the Object from an ObjectValue, which must contain an Object.
bool omEvaluatorObjectValueIsAPrimitive (OMObjectValue objectValue)
Query if the ObjectValue is a Primitive.
MlirAttribute omEvaluatorObjectValueGetPrimitive (OMObjectValue objectValue)
Get the Primitive from an ObjectValue, which must contain a Primitive.
bool omAttrIsAReferenceAttr (MlirAttribute attr)
MlirAttribute omReferenceAttrGetInnerRef (MlirAttribute referenceAttr)
bool omAttrIsAListAttr (MlirAttribute attr)
intptr_t omListAttrGetNumElements (MlirAttribute attr)
MlirAttribute omListAttrGetElement (MlirAttribute attr, intptr_t pos)
Function Documentation
omAttrIsAListAttr()
bool omAttrIsAListAttr (MlirAttribute attr)
Definition at line 202 of file OM.cpp.
References unwrap().
omAttrIsAReferenceAttr()
bool omAttrIsAReferenceAttr (MlirAttribute attr)
Definition at line 189 of file OM.cpp.
References unwrap().
omEvaluatorGetModule()
MlirModule omEvaluatorGetModule (OMEvaluator evaluator)
Get the Module the Evaluator is built from.
Definition at line 98 of file OM.cpp.
References unwrap(), and wrap().
omEvaluatorInstantiate()
OMObject omEvaluatorInstantiate (OMEvaluator evaluator, MlirAttribute className, intptr_t nActualParams, MlirAttribute const * actualParams)
Use the Evaluator to Instantiate an Object from its class name and actual parameters.
Definition at line 70 of file OM.cpp.
References circt::om::Evaluator::instantiate(), unwrap(), and wrap().
omEvaluatorNew()
OMEvaluator omEvaluatorNew (MlirModule mod)
Construct an Evaluator with an IR module.
Definition at line 63 of file OM.cpp.
References unwrap(), and wrap().
omEvaluatorObjectGetField()
OMObjectValue omEvaluatorObjectGetField (OMObject object, MlirAttribute name)
Get a field from an Object, which must contain a field of that name.
Definition at line 124 of file OM.cpp.
References unwrap(), and wrap().
omEvaluatorObjectGetFieldNames()
MlirAttribute omEvaluatorObjectGetFieldNames (OMObject object)
Get an ArrayAttr with the names of the fields in an Object.
Get all the field names from an Object, can be empty if object has no fields.
Definition at line 119 of file OM.cpp.
References unwrap(), and wrap().
omEvaluatorObjectGetType()
MlirType omEvaluatorObjectGetType (OMObject object)
Get the Type from an Object, which will be a ClassType.
Definition at line 114 of file OM.cpp.
References unwrap(), and wrap().
omEvaluatorObjectIsNull()
bool omEvaluatorObjectIsNull (OMObject object)
Query if the Object is null.
Definition at line 108 of file OM.cpp.
Referenced by omEvaluatorObjectValueIsAObject().
omEvaluatorObjectValueGetObject()
OMObject omEvaluatorObjectValueGetObject (OMObjectValue objectValue)
Get the Object from an ObjectValue, which must contain an Object.
Definition at line 166 of file OM.cpp.
References assert(), OMObjectValue::object, and omEvaluatorObjectValueIsAObject().
omEvaluatorObjectValueGetPrimitive()
MlirAttribute omEvaluatorObjectValueGetPrimitive (OMObjectValue objectValue)
Get the Primitive from an ObjectValue, which must contain a Primitive.
Definition at line 179 of file OM.cpp.
References assert(), omEvaluatorObjectValueIsAPrimitive(), and OMObjectValue::primitive.
omEvaluatorObjectValueIsAObject()
bool omEvaluatorObjectValueIsAObject (OMObjectValue objectValue)
Query if the ObjectValue is an Object.
Definition at line 160 of file OM.cpp.
References OMObjectValue::object, and omEvaluatorObjectIsNull().
Referenced by omEvaluatorObjectValueGetObject(), and omEvaluatorObjectValueIsNull().
omEvaluatorObjectValueIsAPrimitive()
bool omEvaluatorObjectValueIsAPrimitive (OMObjectValue objectValue)
Query if the ObjectValue is a Primitive.
Definition at line 173 of file OM.cpp.
References OMObjectValue::primitive.
Referenced by omEvaluatorObjectValueGetPrimitive(), and omEvaluatorObjectValueIsNull().
omEvaluatorObjectValueIsNull()
bool omEvaluatorObjectValueIsNull (OMObjectValue objectValue)
Definition at line 153 of file OM.cpp.
References omEvaluatorObjectValueIsAObject(), and omEvaluatorObjectValueIsAPrimitive().
omListAttrGetElement()
MlirAttribute omListAttrGetElement (MlirAttribute attr, intptr_t pos)
Definition at line 211 of file OM.cpp.
References unwrap(), and wrap().
omListAttrGetNumElements()
intptr_t omListAttrGetNumElements (MlirAttribute attr)
Definition at line 206 of file OM.cpp.
References unwrap().
omReferenceAttrGetInnerRef()
MlirAttribute omReferenceAttrGetInnerRef (MlirAttribute referenceAttr)
Definition at line 193 of file OM.cpp.
References unwrap(), and wrap().
omTypeIsAClassType()
bool omTypeIsAClassType (MlirType type)
Is the Type a ClassType.
Definition at line 34 of file OM.cpp.
References unwrap().
unwrap()
static std::shared_ptr<Object> unwrap (OMObject c) inline static
Definition at line 54 of file OM.cpp.
References OMObject::ptr.
Referenced by circt::esi::buildESIWrapper(), chirrtlTypeGetCMemoryPort(), circtESIAnyTypeGet(), circtESIAppendMlirFile(), circtESIChannelGetInner(), circtESIChannelGetSignaling(), circtESIChannelTypeGet(), circtESIExportCosimSchema(), circtESIListTypeGet(), circtESIListTypeGetElementType(), circtESILookup(), circtESIRegisterGlobalServiceGenerator(), circtESITypeIsAChannelType(), circtESITypeIsAListType(), circtESITypeIsAnAnyType(), circtESIWrapModule(), circtMSFTAppIDAttrGet(), circtMSFTAppIDAttrGetIndex(), circtMSFTAppIDAttrGetName(), circtMSFTAttributeIsALocationVectorAttribute(), circtMSFTAttributeIsAnAppIDAttr(), circtMSFTAttributeIsAPhysicalBoundsAttr(), circtMSFTAttributeIsAPhysLocationAttribute(), circtMSFTCreatePlacementDB(), circtMSFTCreatePrimitiveDB(), circtMSFTDeletePlacementDB(), circtMSFTDeletePrimitiveDB(), circtMSFTLocationVectorAttrGet(), circtMSFTLocationVectorAttrGetElement(), circtMSFTLocationVectorAttrGetNumElements(), circtMSFTLocationVectorAttrGetType(), circtMSFTPhysicalBoundsAttrGet(), circtMSFTPhysLocationAttrGet(), circtMSFTPhysLocationAttrGetNum(), circtMSFTPhysLocationAttrGetPrimitiveType(), circtMSFTPhysLocationAttrGetX(), circtMSFTPhysLocationAttrGetY(), circtMSFTPlacementDBGetInstanceAt(), circtMSFTPlacementDBGetNearestFreeInColumn(), circtMSFTPlacementDBMovePlacement(), circtMSFTPlacementDBPlace(), circtMSFTPlacementDBRemovePlacement(), circtMSFTPlacementDBWalkPlacements(), circtMSFTPrimitiveDBAddPrimitive(), circtMSFTPrimitiveDBIsValidLocation(), circtMSFTReplaceAllUsesWith(), firrtlAttrGetConvention(), firrtlAttrGetEventControl(), firrtlAttrGetMemDir(), firrtlAttrGetMemInit(), firrtlAttrGetNameKind(), firrtlAttrGetPortDirs(), firrtlAttrGetRUW(), firrtlTypeGetAnalog(), firrtlTypeGetAsyncReset(), firrtlTypeGetBundle(), firrtlTypeGetClock(), firrtlTypeGetReset(), firrtlTypeGetSInt(), firrtlTypeGetVector(), hwArrayTypeGet(), hwArrayTypeGetElementType(), hwArrayTypeGetSize(), hwAttrIsAGlobalRefAttr(), hwAttrIsAInnerRefAttr(), hwAttrIsAParamDeclAttr(), hwAttrIsAParamDeclRefAttr(), hwAttrIsAParamVerbatimAttr(), hwGetBitWidth(), hwGlobalRefAttrGet(), hwInnerRefAttrGet(), hwInnerRefAttrGetModule(), hwInnerRefAttrGetName(), hwInOutTypeGet(), hwInOutTypeGetElementType(), hwParamDeclAttrGet(), hwParamDeclAttrGetName(), hwParamDeclAttrGetType(), hwParamDeclAttrGetValue(), hwParamDeclRefAttrGet(), hwParamDeclRefAttrGetName(), hwParamDeclRefAttrGetType(), hwParamIntTypeGet(), hwParamIntTypeGetWidthAttr(), hwParamVerbatimAttrGet(), hwStructTypeGet(), hwStructTypeGetField(), hwStructTypeGetFieldNum(), hwStructTypeGetNumFields(), hwTypeAliasTypeGet(), hwTypeAliasTypeGetCanonicalType(), hwTypeAliasTypeGetInnerType(), hwTypeAliasTypeGetName(), hwTypeAliasTypeGetScope(), hwTypeIsAArrayType(), hwTypeIsAInOut(), hwTypeIsAIntType(), hwTypeIsAStructType(), hwTypeIsATypeAliasType(), hwTypeIsAValueType(), instantiateSystemVerilogMemory(), llhdAttrIsATimeAttr(), llhdPointerTypeGet(), llhdPointerTypeGetElementType(), llhdSignalTypeGet(), llhdSignalTypeGetElementType(), llhdTimeAttrGet(), llhdTimeAttrGetDelta(), llhdTimeAttrGetEpsilon(), llhdTimeAttrGetSeconds(), llhdTimeAttrGetTimeUnit(), llhdTimeTypeGet(), llhdTypeIsAPointerType(), llhdTypeIsASignalType(), llhdTypeIsATimeType(), mlirExportFIRRTL(), mlirExportSplitVerilog(), mlirExportVerilog(), mlirMSFTAddPhysLocationAttr(), mooreChandleTypeGet(), mooreEnumTypeGet(), mooreEnumTypeGetWithBase(), mooreEventTypeGet(), mooreGetSimpleBitVectorSize(), mooreIntTypeGet(), mooreIntTypeGetInt(), mooreIntTypeGetLogic(), mooreIntTypeGetTime(), mooreIsFourValuedType(), mooreIsSimpleBitVectorType(), moorePackedRangeDimTypeGet(), moorePackedUnsizedDimTypeGet(), mooreRealTypeGet(), mooreSimpleBitVectorTypeGet(), mooreStringTypeGet(), mooreUnpackedArrayDimTypeGet(), mooreUnpackedAssocDimTypeGet(), mooreUnpackedAssocDimTypeGetWithIndex(), mooreUnpackedQueueDimTypeGet(), mooreUnpackedQueueDimTypeGetWithBound(), mooreUnpackedRangeDimTypeGet(), mooreUnpackedUnsizedDimTypeGet(), mooreVoidTypeGet(), omAttrIsAListAttr(), omAttrIsAReferenceAttr(), omEvaluatorGetModule(), omEvaluatorInstantiate(), omEvaluatorNew(), omEvaluatorObjectGetField(), omEvaluatorObjectGetFieldNames(), omEvaluatorObjectGetType(), omListAttrGetElement(), omListAttrGetNumElements(), omReferenceAttrGetInnerRef(), omTypeIsAClassType(), operationTypeDupIntRepProc(), operationTypeFreeIntRepProc(), operationTypeUpdateStringProc(), svAttrIsASVAttributeAttr(), svSVAttributeAttrGet(), svSVAttributeAttrGetEmitAsComment(), svSVAttributeAttrGetExpression(), and svSVAttributeAttrGetName().
wrap()
static OMObject wrap (std::shared_ptr< Object > object) inline static
Define our own wrap and unwrap instead of using the usual macro.
This is To handle the std::shared_ptr reference counts appropriately. We want to always create new shared pointers to the Object when we wrap it for C, to increment the reference count. We want to use the shared_from_this functionality to ensure it is unwrapped into C++ with the correct reference count.
Definition at line 49 of file OM.cpp.
References circt::calyx::direction::get().
Referenced by omEvaluatorGetModule(), omEvaluatorInstantiate(), omEvaluatorNew(), omEvaluatorObjectGetField(), omEvaluatorObjectGetFieldNames(), omEvaluatorObjectGetType(), omListAttrGetElement(), and omReferenceAttrGetInnerRef().