CIRCT: /home/runner/work/circt-www/circt-www/circt_src/include/circt-c/Dialect/OM.h File Reference
OM.h File Reference
#include "mlir-c/IR.h"
Classes
struct OMEvaluator
A value type for use in C APIs that just wraps a pointer to an Evaluator.
struct OMObject
A value type for use in C APIs that just wraps a pointer to an Object.
struct OMObjectValue
A value type for use in C APIs that represents an ObjectValue.
Typedefs
typedef struct OMEvaluator OMEvaluator
typedef struct OMObject OMObject
typedef struct OMObjectValue OMObjectValue
Functions
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION (OM, om)
MLIR_CAPI_EXPORTED bool omTypeIsAClassType (MlirType type)
Is the Type a ClassType.
MLIR_CAPI_EXPORTED OMEvaluator omEvaluatorNew (MlirModule mod)
Construct an Evaluator with an IR module.
MLIR_CAPI_EXPORTED OMObject omEvaluatorInstantiate (OMEvaluator evaluator, MlirAttribute className, intptr_t nActualParams, MlirAttribute const *actualParams)
Use the Evaluator to Instantiate an Object from its class name and actual parameters.
MLIR_CAPI_EXPORTED MlirModule omEvaluatorGetModule (OMEvaluator evaluator)
Get the Module the Evaluator is built from.
MLIR_CAPI_EXPORTED bool omEvaluatorObjectIsNull (OMObject object)
Query if the Object is null.
MLIR_CAPI_EXPORTED MlirType omEvaluatorObjectGetType (OMObject object)
Get the Type from an Object, which will be a ClassType.
MLIR_CAPI_EXPORTED OMObjectValue omEvaluatorObjectGetField (OMObject object, MlirAttribute name)
Get a field from an Object, which must contain a field of that name.
MLIR_CAPI_EXPORTED MlirAttribute omEvaluatorObjectGetFieldNames (OMObject object)
Get all the field names from an Object, can be empty if object has no fields.
MLIR_CAPI_EXPORTED bool omEvaluatorObjectValueIsNull (OMObjectValue objectValue)
MLIR_CAPI_EXPORTED bool omEvaluatorObjectValueIsAObject (OMObjectValue objectValue)
Query if the ObjectValue is an Object.
MLIR_CAPI_EXPORTED OMObject omEvaluatorObjectValueGetObject (OMObjectValue objectValue)
Get the Object from an ObjectValue, which must contain an Object.
MLIR_CAPI_EXPORTED bool omEvaluatorObjectValueIsAPrimitive (OMObjectValue objectValue)
Query if the ObjectValue is a Primitive.
MLIR_CAPI_EXPORTED MlirAttribute omEvaluatorObjectValueGetPrimitive (OMObjectValue objectValue)
Get the Primitive from an ObjectValue, which must contain a Primitive.
MLIR_CAPI_EXPORTED bool omAttrIsAReferenceAttr (MlirAttribute attr)
MLIR_CAPI_EXPORTED MlirAttribute omReferenceAttrGetInnerRef (MlirAttribute attr)
MLIR_CAPI_EXPORTED bool omAttrIsAListAttr (MlirAttribute attr)
MLIR_CAPI_EXPORTED intptr_t omListAttrGetNumElements (MlirAttribute attr)
MLIR_CAPI_EXPORTED MlirAttribute omListAttrGetElement (MlirAttribute attr, intptr_t pos)
Typedef Documentation
OMEvaluator
typedef struct OMEvaluator OMEvaluator
Definition at line 37 of file OM.h.
OMObject
typedef struct OMObject OMObject
Definition at line 37 of file OM.h.
OMObjectValue
typedef struct OMObjectValue OMObjectValue
Definition at line 37 of file OM.h.
Function Documentation
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION()
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION (OM , om)
omAttrIsAListAttr()
MLIR_CAPI_EXPORTED bool omAttrIsAListAttr (MlirAttribute attr)
Definition at line 202 of file OM.cpp.
References unwrap().
omAttrIsAReferenceAttr()
MLIR_CAPI_EXPORTED bool omAttrIsAReferenceAttr (MlirAttribute attr)
Definition at line 189 of file OM.cpp.
References unwrap().
omEvaluatorGetModule()
MLIR_CAPI_EXPORTED MlirModule omEvaluatorGetModule (OMEvaluator evaluator)
Get the Module the Evaluator is built from.
Definition at line 98 of file OM.cpp.
References unwrap(), and wrap().
omEvaluatorInstantiate()
MLIR_CAPI_EXPORTED OMObject omEvaluatorInstantiate (OMEvaluator evaluator, MlirAttribute className, intptr_t nActualParams, MlirAttribute const * actualParams)
Use the Evaluator to Instantiate an Object from its class name and actual parameters.
Definition at line 70 of file OM.cpp.
References circt::om::Evaluator::instantiate(), unwrap(), and wrap().
omEvaluatorNew()
MLIR_CAPI_EXPORTED OMEvaluator omEvaluatorNew (MlirModule mod)
Construct an Evaluator with an IR module.
Definition at line 63 of file OM.cpp.
References unwrap(), and wrap().
omEvaluatorObjectGetField()
MLIR_CAPI_EXPORTED OMObjectValue omEvaluatorObjectGetField (OMObject object, MlirAttribute name)
Get a field from an Object, which must contain a field of that name.
Definition at line 124 of file OM.cpp.
References unwrap(), and wrap().
omEvaluatorObjectGetFieldNames()
MLIR_CAPI_EXPORTED MlirAttribute omEvaluatorObjectGetFieldNames (OMObject object)
Get all the field names from an Object, can be empty if object has no fields.
Get all the field names from an Object, can be empty if object has no fields.
Definition at line 119 of file OM.cpp.
References unwrap(), and wrap().
omEvaluatorObjectGetType()
MLIR_CAPI_EXPORTED MlirType omEvaluatorObjectGetType (OMObject object)
Get the Type from an Object, which will be a ClassType.
Definition at line 114 of file OM.cpp.
References unwrap(), and wrap().
omEvaluatorObjectIsNull()
MLIR_CAPI_EXPORTED bool omEvaluatorObjectIsNull (OMObject object)
Query if the Object is null.
Definition at line 108 of file OM.cpp.
Referenced by omEvaluatorObjectValueIsAObject().
omEvaluatorObjectValueGetObject()
MLIR_CAPI_EXPORTED OMObject omEvaluatorObjectValueGetObject (OMObjectValue objectValue)
Get the Object from an ObjectValue, which must contain an Object.
Definition at line 166 of file OM.cpp.
References assert(), OMObjectValue::object, and omEvaluatorObjectValueIsAObject().
omEvaluatorObjectValueGetPrimitive()
MLIR_CAPI_EXPORTED MlirAttribute omEvaluatorObjectValueGetPrimitive (OMObjectValue objectValue)
Get the Primitive from an ObjectValue, which must contain a Primitive.
Definition at line 179 of file OM.cpp.
References assert(), omEvaluatorObjectValueIsAPrimitive(), and OMObjectValue::primitive.
omEvaluatorObjectValueIsAObject()
MLIR_CAPI_EXPORTED bool omEvaluatorObjectValueIsAObject (OMObjectValue objectValue)
Query if the ObjectValue is an Object.
Definition at line 160 of file OM.cpp.
References OMObjectValue::object, and omEvaluatorObjectIsNull().
Referenced by omEvaluatorObjectValueGetObject(), and omEvaluatorObjectValueIsNull().
omEvaluatorObjectValueIsAPrimitive()
MLIR_CAPI_EXPORTED bool omEvaluatorObjectValueIsAPrimitive (OMObjectValue objectValue)
Query if the ObjectValue is a Primitive.
Definition at line 173 of file OM.cpp.
References OMObjectValue::primitive.
Referenced by omEvaluatorObjectValueGetPrimitive(), and omEvaluatorObjectValueIsNull().
omEvaluatorObjectValueIsNull()
MLIR_CAPI_EXPORTED bool omEvaluatorObjectValueIsNull (OMObjectValue objectValue)
Definition at line 153 of file OM.cpp.
References omEvaluatorObjectValueIsAObject(), and omEvaluatorObjectValueIsAPrimitive().
omListAttrGetElement()
MLIR_CAPI_EXPORTED MlirAttribute omListAttrGetElement (MlirAttribute attr, intptr_t pos)
Definition at line 211 of file OM.cpp.
References unwrap(), and wrap().
omListAttrGetNumElements()
MLIR_CAPI_EXPORTED intptr_t omListAttrGetNumElements (MlirAttribute attr)
Definition at line 206 of file OM.cpp.
References unwrap().
omReferenceAttrGetInnerRef()
MLIR_CAPI_EXPORTED MlirAttribute omReferenceAttrGetInnerRef (MlirAttribute attr)
Definition at line 193 of file OM.cpp.
References unwrap(), and wrap().
omTypeIsAClassType()
MLIR_CAPI_EXPORTED bool omTypeIsAClassType (MlirType type)
Is the Type a ClassType.
Definition at line 34 of file OM.cpp.
References unwrap().