CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/Pipeline/PipelineOps.cpp File Reference
PipelineOps.cpp File Reference
#include "circt/Dialect/Pipeline/PipelineOps.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/FunctionImplementation.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/FormatVariadic.h"
#include "circt/Dialect/Pipeline/PipelineDialect.cpp.inc"
#include "circt/Dialect/Pipeline/Pipeline.cpp.inc"
Macros
#define DEBUG_TYPE "pipeline-ops"
#define GET_OP_CLASSES
#define GET_OP_LIST
Functions
static ParseResult parseInitializerList (OpAsmParser &parser, llvm::SmallVector< OpAsmParser::Argument > &inputArguments, llvm::SmallVector< OpAsmParser::UnresolvedOperand > &inputOperands, llvm::SmallVector< Type > &inputTypes, ArrayAttr &inputNames)
static void printInitializerList (OpAsmPrinter &p, ValueRange ins, ArrayRef< BlockArgument > args)
static ParseResult parseExtInitializerList (OpAsmParser &parser, llvm::SmallVector< OpAsmParser::Argument > &extArguments, llvm::SmallVector< OpAsmParser::UnresolvedOperand > &extInputOperands, llvm::SmallVector< Type > &extInputTypes, mlir::ArrayAttr &extInputNames)
static void printExtInitializerList (OpAsmPrinter &p, ValueRange extInputs, ArrayRef< BlockArgument > extArgs)
static ParseResult parseOutputList (OpAsmParser &parser, llvm::SmallVector< Type > &inputTypes, mlir::ArrayAttr &outputNames)
static void printOutputList (OpAsmPrinter &p, TypeRange types, ArrayAttr names)
static ParseResult parseArgAssignment (OpAsmParser &p, OpAsmParser::Argument &arg, OpAsmParser::UnresolvedOperand &operand, Type type)
static ParseResult parseKeywordArgAssignment (OpAsmParser &p, StringRef keyword, OpAsmParser::Argument &arg, OpAsmParser::UnresolvedOperand &operand, Type type)
static ParseResult parsePipelineOp (mlir::OpAsmParser &parser, mlir::OperationState &result)
static void printKeywordAssignment (OpAsmPrinter &p, StringRef keyword, BlockArgument arg, Value value)
template<typename TPipelineOp >
static void printPipelineOp (OpAsmPrinter &p, TPipelineOp op)
static FailureOr< llvm::SmallVector< Block * > > getOrderedStagesFailable (ScheduledPipelineOp op)
static ParseResult parseOptNamedTypedAssignment (OpAsmParser &parser, OpAsmParser::UnresolvedOperand &v, Type &t, StringAttr &name)
static ParseResult parseSingleStageRegister (OpAsmParser &parser, OpAsmParser::UnresolvedOperand &v, Type &t, llvm::SmallVector< OpAsmParser::UnresolvedOperand > &clockGates, StringAttr &name)
ParseResult parseStageRegisters (OpAsmParser &parser, llvm::SmallVector< OpAsmParser::UnresolvedOperand, 4 > &registers, llvm::SmallVector< mlir::Type, 1 > &registerTypes, llvm::SmallVector< OpAsmParser::UnresolvedOperand, 4 > &clockGates, ArrayAttr &clockGatesPerRegister, ArrayAttr &registerNames)
void printStageRegisters (OpAsmPrinter &p, Operation *op, ValueRange registers, TypeRange registerTypes, ValueRange clockGates, ArrayAttr clockGatesPerRegister, ArrayAttr names)
void printPassthroughs (OpAsmPrinter &p, Operation *op, ValueRange passthroughs, TypeRange passthroughTypes, ArrayAttr names)
ParseResult parsePassthroughs (OpAsmParser &parser, llvm::SmallVector< OpAsmParser::UnresolvedOperand, 4 > &passthroughs, llvm::SmallVector< mlir::Type, 1 > &passthroughTypes, ArrayAttr &passthroughNames)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "pipeline-ops"
Definition at line 27 of file PipelineOps.cpp.
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 977 of file PipelineOps.cpp.
GET_OP_LIST
#define GET_OP_LIST
Function Documentation
getOrderedStagesFailable()
static FailureOr<llvm::SmallVector<Block *> > getOrderedStagesFailable (ScheduledPipelineOp op) static
Definition at line 491 of file PipelineOps.cpp.
parseArgAssignment()
static ParseResult parseArgAssignment (OpAsmParser & p, OpAsmParser::Argument & arg, OpAsmParser::UnresolvedOperand & operand, Type type) static
Definition at line 167 of file PipelineOps.cpp.
Referenced by parseKeywordArgAssignment(), and parsePipelineOp().
parseExtInitializerList()
static ParseResult parseExtInitializerList (OpAsmParser & parser, llvm::SmallVector< OpAsmParser::Argument > & extArguments, llvm::SmallVector< OpAsmParser::UnresolvedOperand > & extInputOperands, llvm::SmallVector< Type > & extInputTypes, mlir::ArrayAttr & extInputNames) static
Definition at line 112 of file PipelineOps.cpp.
References parseInitializerList().
Referenced by parsePipelineOp().
parseInitializerList()
static ParseResult parseInitializerList (OpAsmParser & parser, llvm::SmallVector< OpAsmParser::Argument > & inputArguments, llvm::SmallVector< OpAsmParser::UnresolvedOperand > & inputOperands, llvm::SmallVector< Type > & inputTypes, ArrayAttr & inputNames) static
Definition at line 70 of file PipelineOps.cpp.
References circt::calyx::direction::get().
Referenced by parseExtInitializerList(), and parsePipelineOp().
parseKeywordArgAssignment()
static ParseResult parseKeywordArgAssignment (OpAsmParser & p, StringRef keyword, OpAsmParser::Argument & arg, OpAsmParser::UnresolvedOperand & operand, Type type) static
Definition at line 179 of file PipelineOps.cpp.
References parseArgAssignment().
Referenced by parsePipelineOp().
parseOptNamedTypedAssignment()
static ParseResult parseOptNamedTypedAssignment (OpAsmParser & parser, OpAsmParser::UnresolvedOperand & v, Type & t, StringAttr & name) static
Definition at line 641 of file PipelineOps.cpp.
Referenced by parseSingleStageRegister().
parseOutputList()
static ParseResult parseOutputList (OpAsmParser & parser, llvm::SmallVector< Type > & inputTypes, mlir::ArrayAttr & outputNames) static
Definition at line 134 of file PipelineOps.cpp.
References circt::calyx::direction::get().
Referenced by parsePipelineOp().
parsePassthroughs()
ParseResult parsePassthroughs (OpAsmParser & parser, llvm::SmallVector< OpAsmParser::UnresolvedOperand, 4 > & passthroughs, llvm::SmallVector< mlir::Type, 1 > & passthroughTypes, ArrayAttr & passthroughNames)
Definition at line 788 of file PipelineOps.cpp.
parsePipelineOp()
static ParseResult parsePipelineOp (mlir::OpAsmParser & parser, mlir::OperationState & result) static
Definition at line 191 of file PipelineOps.cpp.
References parseArgAssignment(), parseExtInitializerList(), parseInitializerList(), parseKeywordArgAssignment(), and parseOutputList().
parseSingleStageRegister()
static ParseResult parseSingleStageRegister (OpAsmParser & parser, OpAsmParser::UnresolvedOperand & v, Type & t, llvm::SmallVector< OpAsmParser::UnresolvedOperand > & clockGates, StringAttr & name) static
Definition at line 668 of file PipelineOps.cpp.
References parseOptNamedTypedAssignment().
parseStageRegisters()
ParseResult parseStageRegisters (OpAsmParser & parser, llvm::SmallVector< OpAsmParser::UnresolvedOperand, 4 > & registers, llvm::SmallVector< mlir::Type, 1 > & registerTypes, llvm::SmallVector< OpAsmParser::UnresolvedOperand, 4 > & clockGates, ArrayAttr & clockGatesPerRegister, ArrayAttr & registerNames)
Definition at line 690 of file PipelineOps.cpp.
printExtInitializerList()
static void printExtInitializerList (OpAsmPrinter & p, ValueRange extInputs, ArrayRef< BlockArgument > extArgs) static
Definition at line 123 of file PipelineOps.cpp.
References printInitializerList().
Referenced by printPipelineOp().
printInitializerList()
static void printInitializerList (OpAsmPrinter & p, ValueRange ins, ArrayRef< BlockArgument > args) static
Definition at line 100 of file PipelineOps.cpp.
Referenced by printExtInitializerList(), and printPipelineOp().
printKeywordAssignment()
static void printKeywordAssignment (OpAsmPrinter & p, StringRef keyword, BlockArgument arg, Value value) static
Definition at line 303 of file PipelineOps.cpp.
Referenced by printPipelineOp().
printOutputList()
static void printOutputList (OpAsmPrinter & p, TypeRange types, ArrayAttr names) static
Definition at line 156 of file PipelineOps.cpp.
Referenced by printPipelineOp().
printPassthroughs()
void printPassthroughs (OpAsmPrinter & p, Operation * op, ValueRange passthroughs, TypeRange passthroughTypes, ArrayAttr names)
Definition at line 764 of file PipelineOps.cpp.
References seq::reg().
printPipelineOp()
template<typename TPipelineOp > static void printPipelineOp (OpAsmPrinter & p, TPipelineOp op) static
Definition at line 313 of file PipelineOps.cpp.
References printExtInitializerList(), printInitializerList(), printKeywordAssignment(), and printOutputList().
printStageRegisters()
void printStageRegisters (OpAsmPrinter & p, Operation * op, ValueRange registers, TypeRange registerTypes, ValueRange clockGates, ArrayAttr clockGatesPerRegister, ArrayAttr names)
Definition at line 730 of file PipelineOps.cpp.
References seq::reg().