CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/Seq/SeqOps.cpp File Reference
SeqOps.cpp File Reference
#include "circt/Dialect/Seq/SeqOps.h"
#include "circt/Dialect/HW/HWOps.h"
#include "circt/Support/CustomDirectiveImpl.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/PatternMatch.h"
#include "circt/Dialect/HW/HWTypes.h"
#include "llvm/ADT/SmallString.h"
#include "circt/Dialect/Seq/Seq.cpp.inc"
Macros
#define GET_OP_CLASSES
Functions
static std::optional< APInt > getConstantInt (Attribute operand)
Determine the integer value of a constant operand.
static bool isConstantZero (Attribute operand)
Determine whether a constant operand is a zero value.
static bool isConstantOne (Attribute operand)
Determine whether a constant operand is a one value.
static void setNameFromResult (OpAsmParser &parser, OperationState &result)
static bool canElideName (OpAsmPrinter &p, Operation *op)
static ParseResult parseFIFOFlagThreshold (OpAsmParser &parser, IntegerAttr &threshold, Type &outputFlagType, StringRef directive)
ParseResult parseFIFOAFThreshold (OpAsmParser &parser, IntegerAttr &threshold, Type &outputFlagType)
ParseResult parseFIFOAEThreshold (OpAsmParser &parser, IntegerAttr &threshold, Type &outputFlagType)
void printFIFOAFThreshold (OpAsmPrinter &p, Operation *op, IntegerAttr threshold, Type outputFlagType)
void printFIFOAEThreshold (OpAsmPrinter &p, Operation *op, IntegerAttr threshold, Type outputFlagType)
template<bool ClockEnabled>
static ParseResult parseCompReg (OpAsmParser &parser, OperationState &result)
static void printClockEnable (::mlir::OpAsmPrinter &p, CompRegOp op)
static void printClockEnable (::mlir::OpAsmPrinter &p, CompRegClockEnabledOp op)
template<class Op >
static void printCompReg (::mlir::OpAsmPrinter &p, Op op)
template<class Op >
static LogicalResult verifyFirMemMask (Op op)
static bool isConst (Value value)
static bool isConstZero (Value value)
static bool isConstAllOnes (Value value)
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 886 of file SeqOps.cpp.
Function Documentation
canElideName()
static bool canElideName (OpAsmPrinter & p, Operation * op) static
Definition at line 80 of file SeqOps.cpp.
Referenced by printCompReg().
getConstantInt()
static std::optional<APInt> getConstantInt (Attribute operand) static
Determine the integer value of a constant operand.
Definition at line 29 of file SeqOps.cpp.
Referenced by isConstantOne(), and isConstantZero().
isConst()
static bool isConst (Value value) static
Definition at line 794 of file SeqOps.cpp.
isConstAllOnes()
static bool isConstAllOnes (Value value) static
Definition at line 807 of file SeqOps.cpp.
isConstantOne()
static bool isConstantOne (Attribute operand) static
Determine whether a constant operand is a one value.
Definition at line 45 of file SeqOps.cpp.
References getConstantInt().
isConstantZero()
static bool isConstantZero (Attribute operand) static
Determine whether a constant operand is a zero value.
Definition at line 38 of file SeqOps.cpp.
References getConstantInt().
isConstZero()
static bool isConstZero (Value value) static
Definition at line 800 of file SeqOps.cpp.
parseCompReg()
template<bool ClockEnabled> static ParseResult parseCompReg (OpAsmParser & parser, OperationState & result) static
Definition at line 303 of file SeqOps.cpp.
References circt::calyx::direction::get(), and setNameFromResult().
parseFIFOAEThreshold()
ParseResult parseFIFOAEThreshold (OpAsmParser & parser, IntegerAttr & threshold, Type & outputFlagType)
Definition at line 253 of file SeqOps.cpp.
References parseFIFOFlagThreshold().
parseFIFOAFThreshold()
ParseResult parseFIFOAFThreshold (OpAsmParser & parser, IntegerAttr & threshold, Type & outputFlagType)
Definition at line 247 of file SeqOps.cpp.
References parseFIFOFlagThreshold().
parseFIFOFlagThreshold()
static ParseResult parseFIFOFlagThreshold (OpAsmParser & parser, IntegerAttr & threshold, Type & outputFlagType, StringRef directive) static
Definition at line 228 of file SeqOps.cpp.
Referenced by parseFIFOAEThreshold(), and parseFIFOAFThreshold().
printClockEnable() [1/2]
static void printClockEnable (::mlir::OpAsmPrinter & p, CompRegClockEnabledOp op) static
Definition at line 356 of file SeqOps.cpp.
printClockEnable() [2/2]
static void printClockEnable (::mlir::OpAsmPrinter & p, CompRegOp op) static
Definition at line 354 of file SeqOps.cpp.
Referenced by printCompReg().
printCompReg()
template<class Op > static void printCompReg (::mlir::OpAsmPrinter & p, Op op) static
Definition at line 362 of file SeqOps.cpp.
References canElideName(), and printClockEnable().
printFIFOAEThreshold()
void printFIFOAEThreshold (OpAsmPrinter & p, Operation * op, IntegerAttr threshold, Type outputFlagType)
Definition at line 267 of file SeqOps.cpp.
printFIFOAFThreshold()
void printFIFOAFThreshold (OpAsmPrinter & p, Operation * op, IntegerAttr threshold, Type outputFlagType)
Definition at line 259 of file SeqOps.cpp.
setNameFromResult()
static void setNameFromResult (OpAsmParser & parser, OperationState & result) static
Definition at line 69 of file SeqOps.cpp.
References isdigit.
Referenced by parseCompReg().
verifyFirMemMask()
template<class Op > static LogicalResult verifyFirMemMask (Op op) static
Definition at line 776 of file SeqOps.cpp.
References circt::calyx::direction::get().