CIRCT: circt::hw::ModulePortInfo Struct Reference
circt::hw::ModulePortInfo Struct Reference
This holds a decoded list of input/inout and output ports for a module or instance.
#include <HWOpInterfaces.h>
Public Types
using iterator = SmallVector< PortInfo >::iterator
using const_iterator = SmallVector< PortInfo >::const_iterator
Public Member Functions
ModulePortInfo (ArrayRef< PortInfo > inputs, ArrayRef< PortInfo > outputs)
ModulePortInfo (ArrayRef< PortInfo > mergedPorts)
iterator begin_input ()
iterator end_input ()
const_iterator begin_input () const
const_iterator end_input () const
iterator begin_output ()
iterator end_output ()
const_iterator begin_output () const
const_iterator end_output () const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
llvm::iterator_range< iterator > all ()
llvm::iterator_range< const_iterator > all () const
llvm::iterator_range< iterator > inputs ()
llvm::iterator_range< const_iterator > inputs () const
llvm::iterator_range< iterator > outputs ()
llvm::iterator_range< const_iterator > outputs () const
size_t size () const
size_t sizeInputs () const
size_t sizeOutputs () const
PortInfo & at (size_t idx)
PortInfo & atInput (size_t idx)
PortInfo & atOutput (size_t idx)
const PortInfo & at (size_t idx) const
const PortInfo & atInput (size_t idx) const
const PortInfo & atOutput (size_t idx) const
void eraseInput (size_t idx)
Private Attributes
SmallVector< PortInfo > ports
This contains a list of all ports. Input first.
size_t numInputs
This is the index of the first output port.
Detailed Description
This holds a decoded list of input/inout and output ports for a module or instance.
Definition at line 47 of file HWOpInterfaces.h.
Member Typedef Documentation
const_iterator
using circt::hw::ModulePortInfo::const_iterator = SmallVector<PortInfo>::const_iterator
Definition at line 66 of file HWOpInterfaces.h.
iterator
using circt::hw::ModulePortInfo::iterator = SmallVector<PortInfo>::iterator
Definition at line 65 of file HWOpInterfaces.h.
Constructor & Destructor Documentation
ModulePortInfo() [1/2]
circt::hw::ModulePortInfo::ModulePortInfo (ArrayRef< PortInfo > inputs, ArrayRef< PortInfo > outputs) inline explicit
Definition at line 48 of file HWOpInterfaces.h.
References inputs(), numInputs, outputs(), and ports.
ModulePortInfo() [2/2]
circt::hw::ModulePortInfo::ModulePortInfo (ArrayRef< PortInfo > mergedPorts) inline explicit
Definition at line 55 of file HWOpInterfaces.h.
References numInputs, and ports.
Member Function Documentation
all() [1/2]
llvm::iterator_range<iterator> circt::hw::ModulePortInfo::all () inline
Definition at line 80 of file HWOpInterfaces.h.
References begin(), and end().
all() [2/2]
llvm::iterator_range<const_iterator> circt::hw::ModulePortInfo::all () const inline
Definition at line 81 of file HWOpInterfaces.h.
References begin(), and end().
at() [1/2]
PortInfo& circt::hw::ModulePortInfo::at (size_t idx) inline
Definition at line 99 of file HWOpInterfaces.h.
References ports.
Referenced by circt::hw::HWModulePortAccessor::HWModulePortAccessor().
at() [2/2]
const PortInfo& circt::hw::ModulePortInfo::at (size_t idx) const inline
Definition at line 103 of file HWOpInterfaces.h.
References ports.
atInput() [1/2]
PortInfo& circt::hw::ModulePortInfo::atInput (size_t idx) inline
Definition at line 100 of file HWOpInterfaces.h.
References ports.
atInput() [2/2]
const PortInfo& circt::hw::ModulePortInfo::atInput (size_t idx) const inline
Definition at line 104 of file HWOpInterfaces.h.
References ports.
atOutput() [1/2]
PortInfo& circt::hw::ModulePortInfo::atOutput (size_t idx) inline
Definition at line 101 of file HWOpInterfaces.h.
References numInputs, and ports.
atOutput() [2/2]
const PortInfo& circt::hw::ModulePortInfo::atOutput (size_t idx) const inline
Definition at line 105 of file HWOpInterfaces.h.
References numInputs, and ports.
begin() [1/2]
iterator circt::hw::ModulePortInfo::begin () inline
Definition at line 75 of file HWOpInterfaces.h.
References ports.
Referenced by all().
begin() [2/2]
const_iterator circt::hw::ModulePortInfo::begin () const inline
Definition at line 77 of file HWOpInterfaces.h.
References ports.
begin_input() [1/2]
iterator circt::hw::ModulePortInfo::begin_input () inline
Definition at line 67 of file HWOpInterfaces.h.
References ports.
Referenced by inputs().
begin_input() [2/2]
const_iterator circt::hw::ModulePortInfo::begin_input () const inline
Definition at line 69 of file HWOpInterfaces.h.
References ports.
begin_output() [1/2]
iterator circt::hw::ModulePortInfo::begin_output () inline
Definition at line 71 of file HWOpInterfaces.h.
References end_input().
Referenced by outputs().
begin_output() [2/2]
const_iterator circt::hw::ModulePortInfo::begin_output () const inline
Definition at line 73 of file HWOpInterfaces.h.
References end_input().
end() [1/2]
iterator circt::hw::ModulePortInfo::end () inline
Definition at line 76 of file HWOpInterfaces.h.
References ports.
Referenced by all().
end() [2/2]
const_iterator circt::hw::ModulePortInfo::end () const inline
Definition at line 78 of file HWOpInterfaces.h.
References ports.
end_input() [1/2]
iterator circt::hw::ModulePortInfo::end_input () inline
Definition at line 68 of file HWOpInterfaces.h.
References numInputs, and ports.
Referenced by begin_output(), and inputs().
end_input() [2/2]
const_iterator circt::hw::ModulePortInfo::end_input () const inline
Definition at line 70 of file HWOpInterfaces.h.
References numInputs, and ports.
end_output() [1/2]
iterator circt::hw::ModulePortInfo::end_output () inline
Definition at line 72 of file HWOpInterfaces.h.
References ports.
Referenced by outputs().
end_output() [2/2]
const_iterator circt::hw::ModulePortInfo::end_output () const inline
Definition at line 74 of file HWOpInterfaces.h.
References ports.
eraseInput()
void circt::hw::ModulePortInfo::eraseInput (size_t idx) inline
Definition at line 107 of file HWOpInterfaces.h.
References assert(), numInputs, and ports.
inputs() [1/2]
llvm::iterator_range<iterator> circt::hw::ModulePortInfo::inputs () inline
Definition at line 82 of file HWOpInterfaces.h.
References begin_input(), and end_input().
Referenced by circt::msft::MSFTPassCommon::bubbleWiresUp(), ModulePortInfo(), circt::hw::ModulePortLookupInfo::ModulePortLookupInfo(), and circt::hw::PortConverterImpl::run().
inputs() [2/2]
llvm::iterator_range<const_iterator> circt::hw::ModulePortInfo::inputs () const inline
Definition at line 85 of file HWOpInterfaces.h.
References begin_input(), and end_input().
outputs() [1/2]
llvm::iterator_range<iterator> circt::hw::ModulePortInfo::outputs () inline
Definition at line 88 of file HWOpInterfaces.h.
References begin_output(), and end_output().
Referenced by circt::msft::MSFTPassCommon::bubbleWiresUp(), circt::hw::HWModulePortAccessor::HWModulePortAccessor(), ModulePortInfo(), circt::hw::ModulePortLookupInfo::ModulePortLookupInfo(), circt::hw::PortConverterImpl::run(), and circt::hw::PortConverterImpl::updateInstance().
outputs() [2/2]
llvm::iterator_range<const_iterator> circt::hw::ModulePortInfo::outputs () const inline
Definition at line 91 of file HWOpInterfaces.h.
References begin_output(), and end_output().
size()
size_t circt::hw::ModulePortInfo::size () const inline
Definition at line 95 of file HWOpInterfaces.h.
References ports.
sizeInputs()
size_t circt::hw::ModulePortInfo::sizeInputs () const inline
Definition at line 96 of file HWOpInterfaces.h.
References numInputs.
Referenced by circt::msft::MSFTPassCommon::bubbleWiresUp(), circt::hw::HWModulePortAccessor::HWModulePortAccessor(), circt::hw::PortConverterImpl::run(), and circt::hw::PortConverterImpl::updateInstance().
sizeOutputs()
size_t circt::hw::ModulePortInfo::sizeOutputs () const inline
Definition at line 97 of file HWOpInterfaces.h.
References numInputs, and ports.
Referenced by circt::msft::MSFTPassCommon::bubbleWiresUp(), and circt::hw::HWModulePortAccessor::HWModulePortAccessor().
Member Data Documentation
numInputs
size_t circt::hw::ModulePortInfo::numInputs private
This is the index of the first output port.
Definition at line 119 of file HWOpInterfaces.h.
Referenced by atOutput(), end_input(), eraseInput(), ModulePortInfo(), sizeInputs(), and sizeOutputs().
ports
SmallVector<PortInfo> circt::hw::ModulePortInfo::ports private
This contains a list of all ports. Input first.
Definition at line 116 of file HWOpInterfaces.h.
Referenced by at(), atInput(), atOutput(), begin(), begin_input(), end(), end_input(), end_output(), eraseInput(), ModulePortInfo(), size(), and sizeOutputs().
The documentation for this struct was generated from the following file:
/home/runner/work/circt-www/circt-www/circt_src/include/circt/Dialect/HW/HWOpInterfaces.h